import type {
  BenefitFieldRequirement,
  BenefitRequirementDefinition,
  RequirementPredicate,
  SourceAuthority,
} from "./types";

const planAuthorities: SourceAuthority[] = [
  "current_plan_document",
  "current_amendment_or_rider",
  "employer_selection",
  "manual_answer",
];

const eligibilityAuthorities: SourceAuthority[] = [
  "current_plan_document",
  "current_amendment_or_rider",
  "employer_selection",
  "employer_eligibility",
  "manual_answer",
];

// A plan/account document can describe a design without proving that this
// employer selected it for the current period. Offering activation therefore
// requires employer-specific evidence (or an accountable manual answer).
const offeringAuthorities: SourceAuthority[] = [
  "employer_selection",
  "employer_eligibility",
  "rate_or_contribution",
  "manual_answer",
];

const fundingAuthorities: SourceAuthority[] = [
  "current_plan_document",
  "current_amendment_or_rider",
  "employer_selection",
  "rate_or_contribution",
  "manual_answer",
];

const administrationAuthorities: SourceAuthority[] = [
  "current_plan_document",
  "current_amendment_or_rider",
  "administrator_material",
  "employer_selection",
  "manual_answer",
];

const formalAuthorities: SourceAuthority[] = [
  "current_plan_document",
  "current_amendment_or_rider",
  "regulatory_source",
  "approved_boilerplate",
  "manual_answer",
];

const regulatoryAuthorities: SourceAuthority[] = [
  "regulatory_source",
  "approved_boilerplate",
  "current_plan_document",
  "current_amendment_or_rider",
  "manual_answer",
];

const eq = (path: string, value: unknown): RequirementPredicate => ({
  op: "field_equals",
  path,
  value,
});

const inValues = (path: string, values: unknown[]): RequirementPredicate => ({
  op: "field_in",
  path,
  values,
});

const contains = (path: string, value: unknown): RequirementPredicate => ({
  op: "field_contains",
  path,
  value,
});

const any = (...predicates: RequirementPredicate[]): RequirementPredicate => ({
  op: "any",
  predicates,
});

const all = (...predicates: RequirementPredicate[]): RequirementPredicate => ({
  op: "all",
  predicates,
});

function field(value: BenefitFieldRequirement): BenefitFieldRequirement {
  return value;
}

export const hsaRequirements: BenefitRequirementDefinition = {
  benefitType: "hsa",
  title: "Health savings account (HSA)",
  entityKind: "account",
  fields: [
    field({
      id: "hsa.offering.confirmed",
      path: "hsa.offering.confirmed",
      label: "HSA offering",
      description:
        "Confirms that the employer offers or facilitates an HSA; an HSA-qualified medical plan alone is not offering evidence.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: offeringAuthorities,
      validatorIds: ["boolean_true_for_offered_benefit"],
      blockerCode: "HSA_OFFERING_UNCONFIRMED",
      renderPolicy: "never_render",
    }),
    field({
      id: "hsa.identity.display_name",
      path: "hsa.identity.displayName",
      label: "HSA display name",
      description: "The employer-facing name of the HSA program.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: ["nonempty_trimmed_string"],
      blockerCode: "HSA_IDENTITY_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.period.plan_year",
      path: "hsa.period.planYear",
      label: "HSA benefit period",
      description:
        "The employer program period used for eligibility, payroll, and employer-funding descriptions; this is distinct from the calendar-year federal contribution limit.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: ["date_range_valid", "period_label_matches_dates"],
      blockerCode: "HSA_PERIOD_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.eligibility.linked_medical_plans",
      path: "hsa.eligibility.linkedMedicalPlanIds",
      label: "Linked HSA-eligible medical plans",
      description:
        "The specific employer medical plan options whose coverage may satisfy the HDHP component of HSA eligibility.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: eligibilityAuthorities,
      acceptedNotApplicableReasons: ["standalone_hsa_no_employer_medical_plan"],
      validatorIds: ["known_plan_ids", "medical_plans_marked_hsa_eligible"],
      blockerCode: "HSA_ELIGIBLE_PLAN_LINK_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.eligibility.summary",
      path: "hsa.eligibility.summary",
      label: "HSA eligibility summary",
      description:
        "A source-backed summary that HSA contribution eligibility requires qualifying HDHP coverage and no disqualifying coverage, without deciding an individual's tax eligibility.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [
        ...planAuthorities,
        "regulatory_source",
        "approved_boilerplate",
      ],
      validatorIds: ["hsa_eligibility_language_no_individual_determination"],
      blockerCode: "HSA_ELIGIBILITY_SUMMARY_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.eligibility.effective_date_rule",
      path: "hsa.eligibility.effectiveDateRule",
      label: "HSA eligibility effective-date rule",
      description:
        "The date on which employer-program eligibility and payroll contributions may begin.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hsa.offering.payrollContributionsAllowed", true),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: eligibilityAuthorities,
      validatorIds: ["effective_date_rule_parseable"],
      blockerCode: "HSA_EFFECTIVE_DATE_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.administration.custodian_name",
      path: "hsa.administration.custodian.name",
      label: "HSA trustee or custodian",
      description:
        "The bank, trustee, or custodian holding the employee-owned account; it must not be labeled as a reimbursement-claims administrator.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: [
        "nonempty_trimmed_string",
        "hsa_custodian_not_claims_role",
      ],
      blockerCode: "HSA_CUSTODIAN_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.administration.custodian_contact",
      path: "hsa.administration.custodian.contact",
      label: "HSA custodian contact",
      description:
        "The current participant website, telephone number, or account-support contact for the custodian.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "optional",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: ["contact_has_valid_channel"],
      blockerCode: "HSA_CUSTODIAN_CONTACT_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.administration.account_opening",
      path: "hsa.administration.accountOpeningInstructions",
      label: "HSA account-opening instructions",
      description:
        "Any action an eligible employee must take before funds can be deposited into the custodial account.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "optional",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      acceptedExplicitNoneReasons: ["account_opened_automatically"],
      validatorIds: ["instructions_or_automatic_opening"],
      blockerCode: "HSA_OPENING_INSTRUCTIONS_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.ownership.owner",
      path: "hsa.ownership.owner",
      label: "HSA account ownership",
      description: "Identifies the HSA as owned by the eligible individual.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [
        ...planAuthorities,
        "regulatory_source",
        "approved_boilerplate",
      ],
      validatorIds: ["hsa_owner_is_eligible_individual"],
      blockerCode: "HSA_OWNERSHIP_UNRESOLVED",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.ownership.portability_and_rollover",
      path: "hsa.ownership.portabilityAndRollover",
      label: "HSA portability and rollover",
      description:
        "States that the individual's balance is nonforfeitable, carries over, and remains with the owner after employment or coverage changes.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [
        ...planAuthorities,
        "regulatory_source",
        "approved_boilerplate",
      ],
      validatorIds: ["hsa_portability_language"],
      blockerCode: "HSA_PORTABILITY_UNRESOLVED",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.offering.payroll_contributions_allowed",
      path: "hsa.offering.payrollContributionsAllowed",
      label: "Employee HSA payroll contributions",
      description:
        "Whether employees may contribute through payroll under the employer's program.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      validatorIds: ["boolean"],
      blockerCode: "HSA_PAYROLL_CONTRIBUTION_STATUS_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.payroll.election_change_rule",
      path: "hsa.payroll.electionChangeRule",
      label: "HSA payroll election-change rule",
      description:
        "How and when an employee may start or change prospective payroll HSA contributions.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hsa.offering.payrollContributionsAllowed", true),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      validatorIds: ["prospective_election_rule_parseable"],
      blockerCode: "HSA_ELECTION_CHANGE_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.payroll.pay_period_basis",
      path: "hsa.payroll.payPeriodBasis",
      label: "HSA payroll period basis",
      description:
        "The number and type of payroll deductions used when the booklet states a per-pay-period HSA amount.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "optional",
        formal_disclosure: "optional",
      },
      when: eq("hsa.payroll.amountsRenderedPerPayPeriod", true),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      validatorIds: [
        "pay_period_count_positive",
        "pay_period_basis_matches_amounts",
      ],
      blockerCode: "HSA_PAY_PERIOD_BASIS_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.employer_contribution.offered",
      path: "hsa.employerContribution.offered",
      label: "Employer HSA contribution status",
      description: "Whether the employer contributes to employees' HSAs.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      validatorIds: ["boolean"],
      blockerCode: "HSA_EMPLOYER_CONTRIBUTION_STATUS_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.employer_contribution.schedule",
      path: "hsa.employerContribution.schedule",
      label: "Employer HSA contribution schedule",
      description:
        "The source-backed employer contribution amount or tier/formula, including coverage-tier keys where amounts differ.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hsa.employerContribution.offered", true),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      validatorIds: [
        "money_or_formula_schedule_valid",
        "coverage_tiers_unique",
        "contribution_amounts_nonnegative",
      ],
      blockerCode: "HSA_EMPLOYER_CONTRIBUTION_SCHEDULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.employer_contribution.period_basis",
      path: "hsa.employerContribution.periodBasis",
      label: "Employer HSA contribution period basis",
      description:
        "Whether each employer amount is annual, monthly, per pay period, or another explicitly dated basis.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hsa.employerContribution.offered", true),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      validatorIds: ["period_basis_enum", "period_basis_has_effective_year"],
      blockerCode: "HSA_EMPLOYER_CONTRIBUTION_BASIS_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.employer_contribution.deposit_timing",
      path: "hsa.employerContribution.depositTiming",
      label: "Employer HSA deposit timing",
      description:
        "When employer funds are deposited, including installments or a one-time funding date.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hsa.employerContribution.offered", true),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      validatorIds: ["deposit_timing_parseable"],
      blockerCode: "HSA_EMPLOYER_DEPOSIT_TIMING_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.employer_contribution.proration_rule",
      path: "hsa.employerContribution.prorationRule",
      label: "Employer HSA contribution proration",
      description:
        "The new-hire, midyear-enrollment, status-change, or termination proration rule.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "optional",
        formal_disclosure: "conditional",
      },
      when: eq("hsa.employerContribution.offered", true),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      acceptedExplicitNoneReasons: ["employer_contribution_not_prorated"],
      validatorIds: ["proration_rule_or_explicit_none"],
      blockerCode: "HSA_EMPLOYER_PRORATION_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.regulatory_limit.limit_year",
      path: "hsa.regulatoryLimit.calendarYear",
      label: "HSA federal limit year",
      description:
        "The calendar year to which the quoted federal HSA contribution limits apply.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: regulatoryAuthorities,
      validatorIds: ["four_digit_year", "regulatory_period_matches_booklet"],
      blockerCode: "HSA_LIMIT_YEAR_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.regulatory_limit.coverage_tier_limits",
      path: "hsa.regulatoryLimit.coverageTierLimits",
      label: "HSA federal contribution limits",
      description:
        "The self-only and family aggregate contribution limits for the stated calendar year; employer and employee contributions count toward the same limit.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: regulatoryAuthorities,
      validatorIds: [
        "hsa_self_family_limits_present",
        "regulatory_limit_matches_year",
        "aggregate_limit_not_employee_only",
      ],
      blockerCode: "HSA_REGULATORY_LIMIT_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.regulatory_limit.catch_up",
      path: "hsa.regulatoryLimit.catchUp",
      label: "HSA catch-up contribution",
      description:
        "The age threshold and additional annual amount for the stated calendar year.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: regulatoryAuthorities,
      validatorIds: [
        "hsa_catch_up_age_and_amount",
        "regulatory_limit_matches_year",
      ],
      blockerCode: "HSA_CATCH_UP_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.regulatory_limit.partial_year_rule",
      path: "hsa.regulatoryLimit.partialYearRule",
      label: "Partial-year HSA limit rule",
      description:
        "The regulatory month-by-month/last-month-rule qualification that prevents an annual maximum from being presented as universally available.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "optional",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: regulatoryAuthorities,
      validatorIds: ["hsa_partial_year_rule_current"],
      blockerCode: "HSA_PARTIAL_YEAR_RULE_MISSING",
      renderPolicy: "reference_governing_document",
    }),
    field({
      id: "hsa.interactions.health_fsa_mode",
      path: "hsa.interactions.healthFsa.mode",
      label: "Health FSA interaction with HSA",
      description:
        "The actual offered arrangement: none, general-purpose, limited-purpose, post-deductible, suspended, or another documented design—not a universal compatibility flag.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...eligibilityAuthorities, "regulatory_source"],
      acceptedExplicitNoneReasons: ["no_health_fsa_offered"],
      validatorIds: ["hsa_health_fsa_interaction_mode_enum"],
      blockerCode: "HSA_FSA_INTERACTION_UNRESOLVED",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.interactions.health_fsa_impact",
      path: "hsa.interactions.healthFsa.eligibilityImpact",
      label: "Health FSA HSA-eligibility impact",
      description:
        "The HSA eligibility effect of the employer's specific FSA design and any post-deductible transition.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: inValues("hsa.interactions.healthFsa.mode", [
        "general_purpose",
        "limited_purpose",
        "post_deductible",
        "limited_then_post_deductible",
        "suspended",
        "other_documented_design",
      ]),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...eligibilityAuthorities, "regulatory_source"],
      validatorIds: ["hsa_interaction_impact_matches_fsa_mode"],
      blockerCode: "HSA_FSA_IMPACT_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.interactions.hra_mode",
      path: "hsa.interactions.hra.mode",
      label: "HRA interaction with HSA",
      description:
        "The actual offered HRA arrangement: none, general-purpose, limited-purpose, post-deductible, suspended, retirement-only, or another documented design.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...eligibilityAuthorities, "regulatory_source"],
      acceptedExplicitNoneReasons: ["no_hra_offered"],
      validatorIds: ["hsa_hra_interaction_mode_enum"],
      blockerCode: "HSA_HRA_INTERACTION_UNRESOLVED",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.interactions.hra_impact",
      path: "hsa.interactions.hra.eligibilityImpact",
      label: "HRA HSA-eligibility impact",
      description:
        "The HSA eligibility effect of the employer's specific HRA design, deductible threshold, suspension, or retirement-only availability.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: inValues("hsa.interactions.hra.mode", [
        "general_purpose",
        "limited_purpose",
        "post_deductible",
        "limited_then_post_deductible",
        "suspended",
        "retirement_only",
        "other_documented_design",
      ]),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...eligibilityAuthorities, "regulatory_source"],
      validatorIds: ["hsa_interaction_impact_matches_hra_mode"],
      blockerCode: "HSA_HRA_IMPACT_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.interactions.other_disqualifying_coverage",
      path: "hsa.interactions.otherDisqualifyingCoverageSummary",
      label: "Other potentially disqualifying coverage",
      description:
        "A general source-backed summary of Medicare enrollment and other first-dollar health coverage that may affect contribution eligibility, without collecting personal enrollment facts.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: regulatoryAuthorities,
      validatorIds: ["hsa_disqualifying_coverage_summary_current"],
      blockerCode: "HSA_OTHER_COVERAGE_SUMMARY_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hsa.expenses.qualified_expense_reference",
      path: "hsa.expenses.qualifiedExpenseReference",
      label: "HSA qualified-expense reference",
      description:
        "A current authoritative reference for qualified medical expenses and tax consequences; it is not an HRA/FSA claims list.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: regulatoryAuthorities,
      validatorIds: ["current_irs_qualified_expense_reference"],
      blockerCode: "HSA_EXPENSE_REFERENCE_MISSING",
      renderPolicy: "reference_governing_document",
    }),
    field({
      id: "hsa.administration.fees",
      path: "hsa.administration.feeSchedule",
      label: "HSA fee schedule",
      description: "Participant account fees disclosed by the custodian.",
      levels: {
        complete_extraction: "optional",
        safe_booklet: "optional",
        formal_disclosure: "optional",
      },
      material: false,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      acceptedExplicitNoneReasons: ["custodian_discloses_no_participant_fees"],
      validatorIds: ["money_schedule_valid"],
      renderPolicy: "omit_when_absent",
    }),
    field({
      id: "hsa.formal.cafeteria_plan_basis",
      path: "hsa.formal.cafeteriaPlanBasis",
      label: "HSA cafeteria-plan basis",
      description:
        "The plan-document basis for pre-tax payroll HSA contributions; kept out of ordinary booklet copy.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "optional",
        formal_disclosure: "conditional",
      },
      when: eq("hsa.offering.payrollContributionsAllowed", true),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: formalAuthorities,
      validatorIds: ["section_125_document_reference"],
      blockerCode: "HSA_CAFETERIA_PLAN_BASIS_MISSING",
      renderPolicy: "never_render",
    }),
  ],
  invariants: [
    {
      id: "hsa.offering_not_inferred_from_hdhp",
      description:
        "A medical plan's HSA eligibility may trigger a question but never proves that the employer offers or facilitates an HSA.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "hsa.custodian_separate_from_reimbursement_claims",
      description:
        "The trustee/custodian role and employee-owned account must not be normalized as an employer reimbursement account or claims administrator.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "hsa.aggregate_limit",
      description:
        "Employer, employee payroll, and other contributions count together toward the applicable calendar-year HSA contribution limit.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "hsa.no_individual_tax_eligibility_determination",
      description:
        "The booklet may explain general HSA rules but must not assert that a particular employee is tax-eligible or quote that employee's personal remaining limit.",
      gates: ["safe_booklet", "formal_disclosure"],
    },
    {
      id: "hsa.interactions_are_design_specific",
      description:
        "FSA/HRA coexistence is represented by arrangement mode and effect; no single universal compatible/incompatible boolean may replace the design-specific facts.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "hsa.periods_not_conflated",
      description:
        "Employer benefit-plan periods, payroll periods, deposit periods, and federal calendar-year limits retain separate bases and effective years.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
  ],
  researchSources: [
    {
      title:
        "IRS Publication 969, Health Savings Accounts and Other Tax-Favored Health Plans",
      url: "https://www.irs.gov/publications/p969",
      authority: "federal",
    },
    {
      title: "IRS Revenue Procedure 2025-19, 2026 HSA limits",
      url: "https://www.irs.gov/pub/irs-drop/rp-25-19.pdf",
      authority: "federal",
    },
    {
      title: "26 CFR 54.4980G-4, comparable HSA contributions",
      url: "https://www.ecfr.gov/current/title-26/section-54.4980G-4",
      authority: "federal",
    },
    {
      title: "IRS Publication 502, Medical and Dental Expenses",
      url: "https://www.irs.gov/publications/p502",
      authority: "federal",
    },
  ],
  formalDisclosureRequiresSeparateApplicability: true,
};

export const hraRequirements: BenefitRequirementDefinition = {
  benefitType: "hra",
  title: "Health reimbursement arrangement (HRA)",
  entityKind: "account",
  fields: [
    field({
      id: "hra.offering.confirmed",
      path: "hra.offering.confirmed",
      label: "HRA offering",
      description: "Confirms the employer's actual HRA offering.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: offeringAuthorities,
      validatorIds: ["boolean_true_for_offered_benefit"],
      blockerCode: "HRA_OFFERING_UNCONFIRMED",
      renderPolicy: "never_render",
    }),
    field({
      id: "hra.identity.display_name",
      path: "hra.identity.displayName",
      label: "HRA display name",
      description: "The employer-facing program name.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: ["nonempty_trimmed_string"],
      blockerCode: "HRA_IDENTITY_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.design.subtype",
      path: "hra.design.subtype",
      label: "HRA subtype",
      description:
        "The legal/design branch: integrated group-health, retiree-only, QSEHRA, ICHRA, excepted-benefit HRA, or another documented arrangement.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...planAuthorities, "regulatory_source"],
      validatorIds: ["hra_subtype_enum"],
      blockerCode: "HRA_SUBTYPE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.period.plan_year",
      path: "hra.period.planYear",
      label: "HRA plan year",
      description: "The start, end, and label of the HRA plan year.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: ["date_range_valid", "period_label_matches_dates"],
      blockerCode: "HRA_PLAN_YEAR_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.eligibility.classes",
      path: "hra.eligibility.employeeClasses",
      label: "HRA eligible classes",
      description:
        "The employee, retiree, or other participant classes eligible for this HRA.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: eligibilityAuthorities,
      validatorIds: [
        "nonempty_class_list",
        "classes_match_employer_eligibility",
      ],
      blockerCode: "HRA_ELIGIBLE_CLASSES_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.eligibility.dependent_rule",
      path: "hra.eligibility.dependentRule",
      label: "HRA dependent eligibility",
      description:
        "Which spouses, dependents, or other tax dependents may have expenses reimbursed.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: eligibilityAuthorities,
      acceptedExplicitNoneReasons: ["participant_expenses_only"],
      validatorIds: ["dependent_rule_parseable"],
      blockerCode: "HRA_DEPENDENT_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.eligibility.effective_and_termination_rules",
      path: "hra.eligibility.effectiveAndTerminationRules",
      label: "HRA coverage dates",
      description:
        "Rules for initial eligibility, effective date, loss of eligibility, and the expense-incurred cutoff.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: eligibilityAuthorities,
      validatorIds: ["effective_termination_rule_parseable"],
      blockerCode: "HRA_COVERAGE_DATE_RULES_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.administration.administrator_name",
      path: "hra.administration.administrator.name",
      label: "HRA administrator",
      description: "The administrator for this specific HRA.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: [
        "nonempty_trimmed_string",
        "administrator_bound_to_account_id",
      ],
      blockerCode: "HRA_ADMINISTRATOR_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.administration.claims_contact",
      path: "hra.administration.claimsContact",
      label: "HRA reimbursement contact",
      description:
        "The current website, phone, address, or app used for reimbursement questions or submissions.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: ["contact_has_valid_channel"],
      blockerCode: "HRA_CLAIMS_CONTACT_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.funding.design",
      path: "hra.funding.design",
      label: "HRA funding design",
      description:
        "Whether the reimbursement allowance is fixed, tiered, formula-based, credited by period, or another documented design.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      validatorIds: ["hra_funding_design_enum"],
      blockerCode: "HRA_FUNDING_DESIGN_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.funding.allowance_schedule",
      path: "hra.funding.allowanceSchedule",
      label: "HRA allowance schedule",
      description:
        "The fixed amount, tier rows, credit schedule, or deterministic formula for the available employer-funded reimbursement allowance.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      validatorIds: [
        "money_or_formula_schedule_valid",
        "coverage_tiers_unique",
        "allowance_amounts_nonnegative",
      ],
      blockerCode: "HRA_ALLOWANCE_SCHEDULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.funding.period_basis",
      path: "hra.funding.periodBasis",
      label: "HRA allowance period basis",
      description:
        "The annual, monthly, per-pay-period, lifetime, or other explicit basis and effective period for every quoted allowance.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      validatorIds: ["period_basis_enum", "period_basis_has_effective_dates"],
      blockerCode: "HRA_ALLOWANCE_PERIOD_BASIS_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.funding.credit_timing",
      path: "hra.funding.creditTiming",
      label: "HRA credit timing",
      description:
        "When allowance amounts become available and whether they are front-loaded or credited in installments.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      validatorIds: ["credit_timing_parseable"],
      blockerCode: "HRA_CREDIT_TIMING_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.funding.proration_rule",
      path: "hra.funding.prorationRule",
      label: "HRA proration rule",
      description:
        "How allowance amounts change for midyear eligibility, status changes, or termination.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "optional",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      acceptedExplicitNoneReasons: ["allowance_not_prorated"],
      validatorIds: ["proration_rule_or_explicit_none"],
      blockerCode: "HRA_PRORATION_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.funding.employee_contributions",
      path: "hra.funding.employeeContributions",
      label: "HRA employee contributions",
      description:
        "Must resolve explicitly that salary-reduction or other employee contributions are not permitted to the HRA.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [
        ...planAuthorities,
        "regulatory_source",
        "approved_boilerplate",
      ],
      acceptedExplicitNoneReasons: ["hra_employer_funded_only"],
      validatorIds: ["hra_employee_contribution_must_be_none"],
      blockerCode: "HRA_EMPLOYEE_CONTRIBUTION_STATUS_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.balance.carryover_rule",
      path: "hra.balance.carryoverRule",
      label: "HRA balance carryover",
      description:
        "Whether unused amounts carry forward and any cap, ordering, or expiry rule.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      acceptedExplicitNoneReasons: ["unused_balance_forfeits_at_period_end"],
      validatorIds: [
        "carryover_rule_or_explicit_none",
        "money_and_period_bases_present",
      ],
      blockerCode: "HRA_CARRYOVER_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.balance.termination_disposition",
      path: "hra.balance.terminationDisposition",
      label: "HRA balance after coverage ends",
      description:
        "Whether and for how long a former participant may incur or submit expenses, and what happens to any remaining balance.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: ["termination_balance_rule_parseable"],
      blockerCode: "HRA_TERMINATION_BALANCE_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.expenses.eligible_categories",
      path: "hra.expenses.eligibleCategories",
      label: "HRA eligible expense categories",
      description:
        "The plan-specific categories reimbursable under this HRA, including any premium or cost-sharing limitations.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: [
        "nonempty_expense_category_list",
        "hra_expenses_match_subtype",
      ],
      blockerCode: "HRA_ELIGIBLE_EXPENSES_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.expenses.exclusions_reference",
      path: "hra.expenses.exclusionsReference",
      label: "HRA exclusions reference",
      description:
        "The governing source for non-reimbursable expenses; detailed schedules may be referenced rather than reproduced in a booklet.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "optional",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: ["governing_document_reference_valid"],
      blockerCode: "HRA_EXCLUSIONS_REFERENCE_MISSING",
      renderPolicy: "reference_governing_document",
    }),
    field({
      id: "hra.claims.submission_method",
      path: "hra.claims.submissionMethod",
      label: "HRA claim submission",
      description:
        "How participants request reimbursement, including automatic claim forwarding if applicable.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: ["claim_submission_method_enum"],
      blockerCode: "HRA_CLAIM_SUBMISSION_METHOD_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.claims.substantiation_requirements",
      path: "hra.claims.substantiationRequirements",
      label: "HRA substantiation requirements",
      description:
        "The documentation required to substantiate a reimbursement and any automatic-substantiation rules.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: ["substantiation_rule_parseable"],
      blockerCode: "HRA_SUBSTANTIATION_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.claims.runout_deadline",
      path: "hra.claims.runoutDeadline",
      label: "HRA claim runout deadline",
      description:
        "The deadline and period basis for submitting claims incurred during the applicable coverage period.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      acceptedExplicitNoneReasons: ["no_separate_runout_deadline"],
      validatorIds: [
        "deadline_with_time_zone_or_relative_rule",
        "runout_after_incurred_period",
      ],
      blockerCode: "HRA_RUNOUT_DEADLINE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.claims.reimbursement_order",
      path: "hra.claims.reimbursementOrder",
      label: "HRA reimbursement coordination",
      description:
        "The order in which the HRA coordinates with the medical plan, other accounts, or automatic claim forwarding.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "optional",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      acceptedNotApplicableReasons: ["no_other_employer_account_to_coordinate"],
      validatorIds: ["reimbursement_order_acyclic"],
      blockerCode: "HRA_REIMBURSEMENT_ORDER_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.integration.linked_group_health_plans",
      path: "hra.integration.linkedGroupHealthPlanIds",
      label: "Integrated HRA group health plans",
      description:
        "The group health plans with which an integrated HRA is paired.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hra.design.subtype", "integrated_group_health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: eligibilityAuthorities,
      validatorIds: ["known_plan_ids", "hra_integration_plan_link_valid"],
      blockerCode: "HRA_INTEGRATED_PLAN_LINK_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.integration.hsa_interaction_mode",
      path: "hra.integration.hsaInteractionMode",
      label: "HRA interaction with HSA eligibility",
      description:
        "Whether the HRA is general-purpose, limited-purpose, post-deductible, suspended, retirement-only, or another documented design for HSA purposes.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: any(
        eq("hra.design.subtype", "integrated_group_health"),
        eq("hra.design.subtype", "retiree_only"),
        eq("hra.design.subtype", "other_documented_arrangement"),
      ),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...planAuthorities, "regulatory_source"],
      acceptedNotApplicableReasons: ["hsa_not_available_to_eligible_class"],
      validatorIds: ["hsa_hra_interaction_mode_enum"],
      blockerCode: "HRA_HSA_INTERACTION_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.qsehra.employer_eligibility_basis",
      path: "hra.qsehra.employerEligibilityBasis",
      label: "QSEHRA employer eligibility basis",
      description:
        "The source-backed basis for treating the employer as an eligible employer for the QSEHRA; this is a formal compliance fact, not booklet marketing copy.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "optional",
        formal_disclosure: "conditional",
      },
      when: eq("hra.design.subtype", "qsehra"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: formalAuthorities,
      validatorIds: ["qsehra_employer_eligibility_basis_present"],
      blockerCode: "QSEHRA_EMPLOYER_ELIGIBILITY_UNRESOLVED",
      renderPolicy: "never_render",
    }),
    field({
      id: "hra.qsehra.premium_reimbursement_scope",
      path: "hra.qsehra.premiumReimbursementScope",
      label: "QSEHRA premium reimbursement scope",
      description:
        "Which individual-coverage premiums and medical expenses the QSEHRA reimburses.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hra.design.subtype", "qsehra"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: ["qsehra_reimbursement_scope_valid"],
      blockerCode: "QSEHRA_REIMBURSEMENT_SCOPE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.qsehra.minimum_essential_coverage_proof",
      path: "hra.qsehra.minimumEssentialCoverageProof",
      label: "QSEHRA minimum essential coverage substantiation",
      description:
        "The process and timing for substantiating minimum essential coverage before tax-free reimbursement.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hra.design.subtype", "qsehra"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: ["qsehra_mec_substantiation_rule_valid"],
      blockerCode: "QSEHRA_MEC_PROOF_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.qsehra.notice_configuration",
      path: "hra.qsehra.noticeConfiguration",
      label: "QSEHRA notice configuration",
      description:
        "The separately configured statutory notice amount, coverage year, timing, and delivery record.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "optional",
        formal_disclosure: "conditional",
      },
      when: eq("hra.design.subtype", "qsehra"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: formalAuthorities,
      validatorIds: [
        "qsehra_notice_fields_complete",
        "notice_period_matches_allowance",
      ],
      blockerCode: "QSEHRA_NOTICE_CONFIGURATION_MISSING",
      renderPolicy: "never_render",
    }),
    field({
      id: "hra.ichra.class_definition",
      path: "hra.ichra.classDefinition",
      label: "ICHRA employee class",
      description:
        "The regulatory employee class and any waiting-period or rating subdivisions to which the ICHRA is offered.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hra.design.subtype", "ichra"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: eligibilityAuthorities,
      validatorIds: ["ichra_class_definition_valid"],
      blockerCode: "ICHRA_CLASS_DEFINITION_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.ichra.individual_coverage_substantiation",
      path: "hra.ichra.individualCoverageSubstantiation",
      label: "ICHRA individual coverage substantiation",
      description:
        "The annual and ongoing process for substantiating individual health-insurance or Medicare coverage.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hra.design.subtype", "ichra"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: ["ichra_substantiation_rule_valid"],
      blockerCode: "ICHRA_COVERAGE_SUBSTANTIATION_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.ichra.opt_out_rule",
      path: "hra.ichra.optOutRule",
      label: "ICHRA opt-out rule",
      description:
        "How and when an eligible participant may waive or opt out of ICHRA coverage.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hra.design.subtype", "ichra"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: eligibilityAuthorities,
      validatorIds: ["ichra_opt_out_rule_valid"],
      blockerCode: "ICHRA_OPT_OUT_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.ichra.notice_configuration",
      path: "hra.ichra.noticeConfiguration",
      label: "ICHRA notice configuration",
      description:
        "The separately configured participant notice, timing, Marketplace information, amount logic, and delivery record.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "optional",
        formal_disclosure: "conditional",
      },
      when: eq("hra.design.subtype", "ichra"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: formalAuthorities,
      validatorIds: [
        "ichra_notice_fields_complete",
        "notice_period_matches_allowance",
      ],
      blockerCode: "ICHRA_NOTICE_CONFIGURATION_MISSING",
      renderPolicy: "never_render",
    }),
    field({
      id: "hra.ebhra.availability_rule",
      path: "hra.ebhra.availabilityRule",
      label: "Excepted-benefit HRA availability",
      description:
        "The group-health-plan availability condition and uniform-availability rule for the excepted-benefit HRA.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hra.design.subtype", "excepted_benefit_hra"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...eligibilityAuthorities, "regulatory_source"],
      validatorIds: ["ebhra_availability_rule_valid"],
      blockerCode: "EBHRA_AVAILABILITY_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.ebhra.regulatory_limit",
      path: "hra.ebhra.regulatoryLimit",
      label: "Excepted-benefit HRA annual limit",
      description:
        "The indexed federal maximum, effective year, and plan allowance used to verify the excepted-benefit HRA limit.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hra.design.subtype", "excepted_benefit_hra"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: regulatoryAuthorities,
      validatorIds: [
        "ebhra_limit_matches_effective_year",
        "plan_allowance_not_above_limit",
      ],
      blockerCode: "EBHRA_REGULATORY_LIMIT_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.retiree.medicare_coordination",
      path: "hra.retiree.medicareCoordination",
      label: "Retiree HRA Medicare coordination",
      description:
        "The Medicare enrollment, premium reimbursement, and eligible-retiree rules for a retiree-only HRA.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: eq("hra.design.subtype", "retiree_only"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: eligibilityAuthorities,
      acceptedNotApplicableReasons: ["retiree_hra_not_conditioned_on_medicare"],
      validatorIds: ["retiree_hra_coordination_rule_valid"],
      blockerCode: "RETIREE_HRA_COORDINATION_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "hra.formal.claims_and_appeals_reference",
      path: "hra.formal.claimsAndAppealsReference",
      label: "HRA formal claims and appeals procedure",
      description:
        "The governing claims and appeals procedure and administrator; detailed legal text is referenced, not copied into the enrollment booklet.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "optional",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: formalAuthorities,
      validatorIds: ["claims_appeals_reference_valid"],
      blockerCode: "HRA_FORMAL_CLAIMS_PROCEDURE_MISSING",
      renderPolicy: "never_render",
    }),
    field({
      id: "hra.formal.erisa_status",
      path: "hra.formal.erisaStatus",
      label: "HRA ERISA status",
      description:
        "The legal determination of whether and how ERISA disclosure requirements apply; no inference is made from the HRA label alone.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "optional",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: formalAuthorities,
      acceptedNotApplicableReasons: [
        "governmental_plan",
        "church_plan",
        "non_erisa_arrangement",
      ],
      validatorIds: ["erisa_status_enum_with_basis"],
      blockerCode: "HRA_ERISA_STATUS_UNRESOLVED",
      renderPolicy: "never_render",
    }),
    field({
      id: "hra.formal.cobra_or_continuation",
      path: "hra.formal.cobraOrContinuation",
      label: "HRA continuation coverage applicability",
      description:
        "The separately determined federal or state continuation rules, including subtype and employer-size applicability.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "optional",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: formalAuthorities,
      acceptedNotApplicableReasons: [
        "federal_cobra_employer_size_exception",
        "governmental_continuation_rules_separate",
        "arrangement_not_subject_to_continuation",
      ],
      validatorIds: ["continuation_applicability_has_legal_basis"],
      blockerCode: "HRA_CONTINUATION_STATUS_UNRESOLVED",
      renderPolicy: "never_render",
    }),
  ],
  invariants: [
    {
      id: "hra.employer_funded_only",
      description:
        "An HRA is employer funded; salary-reduction or other employee contributions must not be represented as HRA funding.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "hra.allowance_not_cash_account",
      description:
        "The HRA allowance is a reimbursement promise subject to plan terms, not an employee-owned bank account or automatically vested cash balance.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "hra.subtype_controls_requirements",
      description:
        "Integrated HRA, retiree-only HRA, QSEHRA, ICHRA, and excepted-benefit HRA rules are not interchangeable; subtype conditions must be resolved before publication.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "hra.periods_not_conflated",
      description:
        "Plan year, allowance basis, credit timing, incurred-date period, carryover, and runout deadline retain separate explicit period bases.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "hra.account_specific_administrator",
      description:
        "Administrator, allowance, eligible expenses, and claims rules remain bound to this HRA and are not borrowed from another account offered by the employer.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "hra.formal_notices_separate",
      description:
        "An enrollment booklet does not replace an applicable SPD, plan document, ICHRA/QSEHRA notice, COBRA notice, or claims procedure.",
      gates: ["safe_booklet", "formal_disclosure"],
    },
  ],
  researchSources: [
    {
      title:
        "IRS Publication 969, Health Savings Accounts and Other Tax-Favored Health Plans",
      url: "https://www.irs.gov/publications/p969",
      authority: "federal",
    },
    {
      title: "IRS Notice 2013-54, application of market-reform rules to HRAs",
      url: "https://www.irs.gov/pub/irs-drop/n-13-54.pdf",
      authority: "federal",
    },
    {
      title: "IRS Notice 2017-67, QSEHRA guidance",
      url: "https://www.irs.gov/pub/irs-drop/n-17-67.pdf",
      authority: "federal",
    },
    {
      title: "CMS Individual Coverage HRA model notice and resources",
      url: "https://www.cms.gov/marketplace/technical-assistance-resources/individual-coverage-hra",
      authority: "federal",
    },
    {
      title:
        "Federal final rule, Health Reimbursement Arrangements and Other Account-Based Group Health Plans",
      url: "https://www.federalregister.gov/documents/2019/06/20/2019-12571/health-reimbursement-arrangements-and-other-account-based-group-health-plans",
      authority: "federal",
    },
    {
      title: "29 CFR 2520.102-3, contents of summary plan descriptions",
      url: "https://www.ecfr.gov/current/title-29/section-2520.102-3",
      authority: "federal",
    },
  ],
  formalDisclosureRequiresSeparateApplicability: true,
};

export const fsaRequirements: BenefitRequirementDefinition = {
  benefitType: "fsa",
  title: "Flexible spending arrangements (FSA)",
  entityKind: "product_collection",
  fields: [
    field({
      id: "fsa.offering.confirmed",
      path: "fsa.offering.confirmed",
      label: "FSA offering",
      description:
        "Confirms that at least one specific FSA arrangement is offered.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: offeringAuthorities,
      validatorIds: ["boolean_true_for_offered_benefit"],
      blockerCode: "FSA_OFFERING_UNCONFIRMED",
      renderPolicy: "never_render",
    }),
    field({
      id: "fsa.arrangements.offered_types",
      path: "fsa.arrangements.offeredTypes",
      label: "Offered FSA arrangements",
      description:
        "The exact offered branches: health, limited-purpose health, post-deductible health, and/or dependent-care FSA.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: eligibilityAuthorities,
      validatorIds: ["fsa_offered_types_nonempty_unique", "fsa_type_enum"],
      blockerCode: "FSA_TYPES_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.period.plan_year",
      path: "fsa.period.planYear",
      label: "FSA plan year",
      description:
        "The start, end, and label of the cafeteria-plan/FSA plan year.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: ["date_range_valid", "period_label_matches_dates"],
      blockerCode: "FSA_PLAN_YEAR_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.administration.administrator_name",
      path: "fsa.administration.administrator.name",
      label: "FSA administrator",
      description: "The administrator bound to the offered FSA arrangements.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: [
        "nonempty_trimmed_string",
        "administrator_bound_to_account_id",
      ],
      blockerCode: "FSA_ADMINISTRATOR_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.administration.contact",
      path: "fsa.administration.contact",
      label: "FSA administrator contact",
      description:
        "The current participant website, telephone, address, or app.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: ["contact_has_valid_channel"],
      blockerCode: "FSA_ADMINISTRATOR_CONTACT_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.administration.fee_schedule",
      path: "fsa.administration.feeSchedule",
      label: "FSA participant fee schedule",
      description:
        "Participant-paid account or administrative fees with amount, unit, frequency, maximum, and affected arrangement.",
      levels: {
        complete_extraction: "optional",
        safe_booklet: "optional",
        formal_disclosure: "optional",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      acceptedExplicitNoneReasons: [
        "administrator_discloses_no_participant_fees",
      ],
      validatorIds: ["money_has_unit_and_frequency", "fee_scope_is_qualified"],
      renderPolicy: "omit_when_absent",
    }),
    field({
      id: "fsa.eligibility.classes",
      path: "fsa.eligibility.employeeClasses",
      label: "FSA eligible classes",
      description:
        "The employee classes eligible to elect each offered FSA arrangement.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: eligibilityAuthorities,
      validatorIds: [
        "fsa_classes_by_arrangement",
        "classes_match_employer_eligibility",
      ],
      blockerCode: "FSA_ELIGIBLE_CLASSES_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.elections.enrollment_window",
      path: "fsa.elections.enrollmentWindow",
      label: "FSA election window",
      description:
        "The plan-year election deadline and new-hire election timing, with dates or deterministic relative rules.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: eligibilityAuthorities,
      validatorIds: [
        "enrollment_window_parseable",
        "deadline_period_matches_plan_year",
      ],
      blockerCode: "FSA_ELECTION_WINDOW_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.elections.change_rule",
      path: "fsa.elections.changeRule",
      label: "FSA election-change rule",
      description:
        "The prospective election rule and plan-specific permitted-change-event process; no event is promised unless supported by the plan.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: ["section_125_election_change_rule_parseable"],
      blockerCode: "FSA_ELECTION_CHANGE_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.elections.payroll_period_basis",
      path: "fsa.elections.payrollPeriodBasis",
      label: "FSA payroll period basis",
      description:
        "The payroll count and basis used to derive a per-pay-period deduction from an annual election.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "optional",
        formal_disclosure: "optional",
      },
      when: eq("fsa.elections.amountsRenderedPerPayPeriod", true),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      validatorIds: [
        "pay_period_count_positive",
        "annual_to_period_calculation_exact",
      ],
      blockerCode: "FSA_PAYROLL_PERIOD_BASIS_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.claims.submission_method",
      path: "fsa.claims.submissionMethod",
      label: "FSA claim submission",
      description:
        "How reimbursement claims and required documentation are submitted for each arrangement.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: ["claim_submission_methods_by_arrangement"],
      blockerCode: "FSA_CLAIM_SUBMISSION_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.claims.substantiation",
      path: "fsa.claims.substantiationRequirements",
      label: "FSA substantiation",
      description:
        "Documentation and independent-substantiation requirements, including debit-card follow-up where applicable.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: ["fsa_substantiation_rule_parseable"],
      blockerCode: "FSA_SUBSTANTIATION_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.claims.runout_deadline",
      path: "fsa.claims.runoutDeadline",
      label: "FSA claim runout deadline",
      description:
        "The deadline, applicable incurred period, and arrangement branch for submitting reimbursement claims.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: administrationAuthorities,
      validatorIds: ["runout_by_arrangement", "runout_after_incurred_period"],
      blockerCode: "FSA_RUNOUT_DEADLINE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.health.election_limit",
      path: "fsa.health.electionLimit",
      label: "Health FSA election limit",
      description:
        "The employer plan maximum and applicable indexed federal salary-reduction maximum, each with its effective plan/tax year.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...fundingAuthorities, "regulatory_source"],
      validatorIds: [
        "health_fsa_plan_and_statutory_limits",
        "limit_effective_year_present",
        "plan_limit_not_above_statutory_limit",
      ],
      blockerCode: "HEALTH_FSA_ELECTION_LIMIT_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.health.employer_contribution",
      path: "fsa.health.employerContribution",
      label: "Health FSA employer contribution",
      description:
        "Any employer contribution or matching formula and its period basis.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: fundingAuthorities,
      acceptedExplicitNoneReasons: ["no_employer_health_fsa_contribution"],
      validatorIds: ["money_or_formula_with_period_basis"],
      blockerCode: "HEALTH_FSA_EMPLOYER_CONTRIBUTION_STATUS_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.health.eligible_expenses",
      path: "fsa.health.eligibleExpenses",
      label: "Health FSA eligible expenses",
      description:
        "The plan-specific health expense scope and authoritative exclusions/reference.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...planAuthorities, "regulatory_source"],
      validatorIds: ["health_fsa_expense_scope_valid"],
      blockerCode: "HEALTH_FSA_EXPENSE_SCOPE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.health.uniform_coverage_rule",
      path: "fsa.health.uniformCoverageRule",
      label: "Health FSA uniform coverage",
      description:
        "Confirms that the elected annual health FSA amount is available during coverage as required by the plan, distinct from dependent-care reimbursement.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [
        ...planAuthorities,
        "regulatory_source",
        "approved_boilerplate",
      ],
      validatorIds: ["health_fsa_uniform_coverage_rule"],
      blockerCode: "HEALTH_FSA_UNIFORM_COVERAGE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.health.carryover",
      path: "fsa.health.carryover",
      label: "Health FSA carryover",
      description:
        "The plan's carryover amount, indexed maximum, source year, destination year, and availability timing.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...planAuthorities, "regulatory_source"],
      acceptedExplicitNoneReasons: ["health_fsa_no_carryover"],
      validatorIds: [
        "carryover_amount_with_source_destination_years",
        "carryover_not_above_indexed_maximum",
      ],
      blockerCode: "HEALTH_FSA_CARRYOVER_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.health.grace_period",
      path: "fsa.health.gracePeriod",
      label: "Health FSA grace period",
      description:
        "The post-plan-year period for incurring health FSA expenses, with start/end dates or a deterministic duration.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      acceptedExplicitNoneReasons: ["health_fsa_no_grace_period"],
      validatorIds: [
        "grace_period_duration_valid",
        "grace_period_dates_match_plan_year",
      ],
      blockerCode: "HEALTH_FSA_GRACE_PERIOD_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.health.forfeiture_rule",
      path: "fsa.health.forfeitureRule",
      label: "Health FSA forfeiture rule",
      description:
        "The use-or-lose rule after applying the plan's carryover/grace/runout provisions.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [
        ...planAuthorities,
        "regulatory_source",
        "approved_boilerplate",
      ],
      validatorIds: ["forfeiture_rule_matches_carryover_and_grace"],
      blockerCode: "HEALTH_FSA_FORFEITURE_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.health.hsa_interaction_mode",
      path: "fsa.health.hsaInteractionMode",
      label: "Health FSA interaction with HSA",
      description:
        "The actual effect of general-purpose health FSA coverage and any carryover/grace-period coverage on HSA contribution eligibility.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...planAuthorities, "regulatory_source"],
      acceptedNotApplicableReasons: ["hsa_not_offered_to_fsa_eligible_class"],
      validatorIds: ["hsa_health_fsa_interaction_mode_enum"],
      blockerCode: "HEALTH_FSA_HSA_INTERACTION_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.limited_purpose.election_limit",
      path: "fsa.limitedPurpose.electionLimit",
      label: "Limited-purpose FSA election limit",
      description:
        "The plan maximum and applicable indexed health-FSA salary-reduction maximum, with effective year.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "limited_purpose_health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...fundingAuthorities, "regulatory_source"],
      validatorIds: [
        "health_fsa_plan_and_statutory_limits",
        "limit_effective_year_present",
      ],
      blockerCode: "LPFSA_ELECTION_LIMIT_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.limited_purpose.eligible_expenses",
      path: "fsa.limitedPurpose.eligibleExpenses",
      label: "Limited-purpose FSA eligible expenses",
      description:
        "The pre-deductible dental, vision, preventive, or other plan-specific limited expense categories.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "limited_purpose_health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: ["limited_purpose_expense_scope_valid"],
      blockerCode: "LPFSA_EXPENSE_SCOPE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.limited_purpose.post_deductible_transition",
      path: "fsa.limitedPurpose.postDeductibleTransition",
      label: "Limited-purpose FSA post-deductible transition",
      description:
        "Whether coverage expands after a deductible and, if so, the threshold, applicable medical plan, evidence process, and effective date.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "limited_purpose_health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      acceptedExplicitNoneReasons: [
        "limited_purpose_never_converts_post_deductible",
      ],
      validatorIds: ["post_deductible_transition_or_explicit_none"],
      blockerCode: "LPFSA_POST_DEDUCTIBLE_TRANSITION_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.limited_purpose.carryover",
      path: "fsa.limitedPurpose.carryover",
      label: "Limited-purpose FSA carryover",
      description:
        "The limited-purpose FSA carryover amount and source/destination plan years.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "limited_purpose_health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...planAuthorities, "regulatory_source"],
      acceptedExplicitNoneReasons: ["limited_purpose_fsa_no_carryover"],
      validatorIds: ["carryover_amount_with_source_destination_years"],
      blockerCode: "LPFSA_CARRYOVER_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.limited_purpose.grace_period",
      path: "fsa.limitedPurpose.gracePeriod",
      label: "Limited-purpose FSA grace period",
      description: "The limited-purpose FSA grace-period rule and dates.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "limited_purpose_health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      acceptedExplicitNoneReasons: ["limited_purpose_fsa_no_grace_period"],
      validatorIds: [
        "grace_period_duration_valid",
        "grace_period_dates_match_plan_year",
      ],
      blockerCode: "LPFSA_GRACE_PERIOD_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.limited_purpose.hsa_interaction",
      path: "fsa.limitedPurpose.hsaInteraction",
      label: "Limited-purpose FSA HSA interaction",
      description:
        "The source-backed HSA eligibility effect before and after any post-deductible transition.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "limited_purpose_health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...planAuthorities, "regulatory_source"],
      validatorIds: ["limited_purpose_hsa_interaction_valid"],
      blockerCode: "LPFSA_HSA_INTERACTION_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.post_deductible.election_limit",
      path: "fsa.postDeductible.electionLimit",
      label: "Post-deductible FSA election limit",
      description:
        "The plan maximum and applicable indexed health-FSA salary-reduction maximum, with effective year.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "post_deductible_health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...fundingAuthorities, "regulatory_source"],
      validatorIds: [
        "health_fsa_plan_and_statutory_limits",
        "limit_effective_year_present",
      ],
      blockerCode: "POST_DEDUCTIBLE_FSA_ELECTION_LIMIT_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.post_deductible.threshold",
      path: "fsa.postDeductible.threshold",
      label: "Post-deductible FSA threshold",
      description:
        "The deductible amount, coverage tier, linked HDHP, satisfaction method, and date after which reimbursements may begin.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "post_deductible_health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: [
        "post_deductible_threshold_by_tier",
        "linked_hdhp_exists",
        "threshold_period_basis_present",
      ],
      blockerCode: "POST_DEDUCTIBLE_FSA_THRESHOLD_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.post_deductible.eligible_expenses",
      path: "fsa.postDeductible.eligibleExpenses",
      label: "Post-deductible FSA eligible expenses",
      description:
        "The expense categories reimbursable after the applicable deductible threshold is satisfied.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "post_deductible_health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      validatorIds: ["post_deductible_expense_scope_valid"],
      blockerCode: "POST_DEDUCTIBLE_FSA_EXPENSE_SCOPE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.post_deductible.hsa_interaction",
      path: "fsa.postDeductible.hsaInteraction",
      label: "Post-deductible FSA HSA interaction",
      description:
        "The source-backed HSA eligibility effect of the exact deductible threshold and coverage timing.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "post_deductible_health"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...planAuthorities, "regulatory_source"],
      validatorIds: ["post_deductible_hsa_interaction_valid"],
      blockerCode: "POST_DEDUCTIBLE_FSA_HSA_INTERACTION_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.dependent_care.election_limit",
      path: "fsa.dependentCare.electionLimit",
      label: "Dependent-care FSA election limit",
      description:
        "The employer plan maximum and applicable federal exclusion amount for the stated tax year and filing-status basis, without calculating an individual's allowable exclusion.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "dependent_care"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...fundingAuthorities, "regulatory_source"],
      validatorIds: [
        "dcfsa_plan_and_federal_limits",
        "limit_effective_tax_year_present",
        "no_individual_tax_limit_assertion",
      ],
      blockerCode: "DCFSA_ELECTION_LIMIT_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.dependent_care.eligible_persons_and_services",
      path: "fsa.dependentCare.eligiblePersonsAndServices",
      label: "Dependent-care FSA eligible persons and services",
      description:
        "The general qualifying-person, work-related-care, provider, and service rules, with an authoritative tax reference rather than a personal eligibility determination.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "dependent_care"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [...planAuthorities, "regulatory_source"],
      validatorIds: ["dcfsa_general_eligibility_summary_current"],
      blockerCode: "DCFSA_ELIGIBLE_CARE_RULES_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.dependent_care.reimbursement_balance_rule",
      path: "fsa.dependentCare.reimbursementBalanceRule",
      label: "Dependent-care FSA reimbursement availability",
      description:
        "States that reimbursement is limited to the dependent-care contributions credited when the claim is processed, unlike health FSA uniform coverage.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "dependent_care"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [
        ...planAuthorities,
        "regulatory_source",
        "approved_boilerplate",
      ],
      validatorIds: ["dcfsa_reimbursement_limited_to_credited_balance"],
      blockerCode: "DCFSA_REIMBURSEMENT_BALANCE_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.dependent_care.grace_period",
      path: "fsa.dependentCare.gracePeriod",
      label: "Dependent-care FSA grace period",
      description:
        "Any post-plan-year period for incurring dependent-care expenses, with dates or duration.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "dependent_care"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planAuthorities,
      acceptedExplicitNoneReasons: ["dependent_care_fsa_no_grace_period"],
      validatorIds: [
        "grace_period_duration_valid",
        "grace_period_dates_match_plan_year",
      ],
      blockerCode: "DCFSA_GRACE_PERIOD_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.dependent_care.forfeiture_rule",
      path: "fsa.dependentCare.forfeitureRule",
      label: "Dependent-care FSA forfeiture rule",
      description:
        "The use-or-lose rule after the arrangement's grace period and runout deadline.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "dependent_care"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: [
        ...planAuthorities,
        "regulatory_source",
        "approved_boilerplate",
      ],
      validatorIds: ["dcfsa_forfeiture_rule_matches_grace_and_runout"],
      blockerCode: "DCFSA_FORFEITURE_RULE_MISSING",
      renderPolicy: "render",
    }),
    field({
      id: "fsa.dependent_care.tax_reference",
      path: "fsa.dependentCare.taxReference",
      label: "Dependent-care tax reference",
      description:
        "A current IRS reference for earned-income, filing-status, qualifying-person, provider-reporting, and dependent-care-credit coordination rules.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: contains("fsa.arrangements.offeredTypes", "dependent_care"),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: regulatoryAuthorities,
      validatorIds: ["current_irs_dependent_care_reference"],
      blockerCode: "DCFSA_TAX_REFERENCE_MISSING",
      renderPolicy: "reference_governing_document",
    }),
    field({
      id: "fsa.formal.plan_document_reference",
      path: "fsa.formal.planDocumentReference",
      label: "FSA cafeteria-plan document",
      description:
        "The governing Section 125/FSA plan document and amendments; it is not replaced by the enrollment booklet.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "optional",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: formalAuthorities,
      validatorIds: ["section_125_document_reference"],
      blockerCode: "FSA_PLAN_DOCUMENT_MISSING",
      renderPolicy: "never_render",
    }),
    field({
      id: "fsa.formal.claims_and_appeals_reference",
      path: "fsa.formal.claimsAndAppealsReference",
      label: "FSA formal claims and appeals procedure",
      description:
        "The governing claims and appeals procedure; detailed legal text is referenced rather than copied into enrollment copy.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "optional",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: formalAuthorities,
      validatorIds: ["claims_appeals_reference_valid"],
      blockerCode: "FSA_FORMAL_CLAIMS_PROCEDURE_MISSING",
      renderPolicy: "never_render",
    }),
    field({
      id: "fsa.formal.erisa_status",
      path: "fsa.formal.erisaStatus",
      label: "FSA ERISA status",
      description:
        "The legal determination for ERISA disclosure applicability by arrangement; it is not inferred solely from the FSA label.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "optional",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: formalAuthorities,
      acceptedNotApplicableReasons: [
        "governmental_plan",
        "church_plan",
        "non_erisa_arrangement",
      ],
      validatorIds: ["erisa_status_by_arrangement_with_basis"],
      blockerCode: "FSA_ERISA_STATUS_UNRESOLVED",
      renderPolicy: "never_render",
    }),
  ],
  invariants: [
    {
      id: "fsa.only_offered_branches_render",
      description:
        "Only FSA arrangement branches supported by current employer evidence may be extracted as offered or rendered.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "fsa.health_and_dependent_care_not_conflated",
      description:
        "Health, limited-purpose, post-deductible, and dependent-care FSAs retain separate limits, expenses, availability, carryover/grace, and forfeiture rules.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "fsa.health_uniform_coverage_only",
      description:
        "Health-FSA uniform coverage must not be applied to dependent-care FSA reimbursements, which are limited to the credited account balance.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "fsa.health_carryover_and_grace_not_both",
      description:
        "For the same health-FSA arrangement and plan year, a standard carryover and grace period must not both be represented as available unless a current, specifically applicable regulatory exception supports it.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "fsa.hsa_interaction_includes_extended_coverage",
      description:
        "HSA-interaction analysis includes health-FSA carryover and grace-period coverage and any post-deductible transition, not merely the employee's current salary-reduction election.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "fsa.periods_not_conflated",
      description:
        "Plan year, tax-year limits, payroll periods, incurred-date periods, grace periods, carryover source/destination years, and runout deadlines retain separate bases.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "fsa.no_personal_tax_determination",
      description:
        "The booklet may state general tax limits and rules but must not determine an individual's allowable dependent-care exclusion, HSA eligibility, or tax liability.",
      gates: ["safe_booklet", "formal_disclosure"],
    },
    {
      id: "fsa.account_specific_administrator",
      description:
        "Administrator, elections, claims, and deadlines remain bound to the applicable arrangement and are not borrowed from another employer account.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
  ],
  researchSources: [
    {
      title:
        "IRS Publication 969, Health FSAs and other tax-favored health plans",
      url: "https://www.irs.gov/publications/p969",
      authority: "federal",
    },
    {
      title: "IRS Publication 15-B, cafeteria plans and health FSA limits",
      url: "https://www.irs.gov/publications/p15b",
      authority: "federal",
    },
    {
      title: "IRS Publication 503, Child and Dependent Care Expenses",
      url: "https://www.irs.gov/publications/p503",
      authority: "federal",
    },
    {
      title: "26 USC 125, Cafeteria plans",
      url: "https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title26-section125&num=0&edition=prelim",
      authority: "federal",
    },
    {
      title: "IRS Revenue Procedure 2025-32, 2026 indexed tax amounts",
      url: "https://www.irs.gov/pub/irs-drop/rp-25-32.pdf",
      authority: "federal",
    },
    {
      title: "29 CFR 2520.102-3, contents of summary plan descriptions",
      url: "https://www.ecfr.gov/current/title-29/section-2520.102-3",
      authority: "federal",
    },
  ],
  formalDisclosureRequiresSeparateApplicability: true,
};
