import type {
  BenefitFieldRequirement,
  BenefitRequirementDefinition,
  RequirementPredicate,
  SourceAuthority,
} from "./types";
import {
  employerOfferingAuthorities,
  employerPlanAuthorities,
  planDesignAuthorities,
  requirement,
} from "./types";

const identityAuthorities: SourceAuthority[] = [
  "current_plan_document",
  "current_amendment_or_rider",
  "employer_selection",
  "administrator_material",
  "manual_answer",
];

const contactAuthorities: SourceAuthority[] = [
  "current_plan_document",
  "current_amendment_or_rider",
  "administrator_material",
  "employer_selection",
  "manual_answer",
];

const legalAuthorities: SourceAuthority[] = [
  "current_plan_document",
  "current_amendment_or_rider",
  "regulatory_source",
  "approved_boilerplate",
  "manual_answer",
];

const fieldEquals = (path: string, value: unknown): RequirementPredicate => ({
  op: "field_equals",
  path,
  value,
});

const fieldIn = (path: string, values: unknown[]): RequirementPredicate => ({
  op: "field_in",
  path,
  values,
});

function commonPlanFields(
  benefit: "medical" | "dental" | "vision",
): BenefitFieldRequirement[] {
  const root = `plans.${benefit}`;
  const title = benefit[0].toUpperCase() + benefit.slice(1);
  return [
    requirement({
      id: `${benefit}.offering.selectedByEmployer`,
      path: `${root}.offering.selectedByEmployer`,
      label: `${title} employer selection`,
      description:
        "Positive employer-specific evidence that this exact option is offered; document presence, a generic carrier brochure, and a rate row alone are insufficient.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: employerOfferingAuthorities,
      validatorIds: ["employer_selection_is_positive", "selected_option_is_unambiguous"],
      blockerCode: `${benefit.toUpperCase()}_EMPLOYER_SELECTION_UNPROVEN`,
      renderPolicy: "never_render",
    }),
    requirement({
      id: `${benefit}.identity.planName`,
      path: `${root}.identity.planName`,
      label: `${title} plan name`,
      description: "Exact current plan or option name, not a generic benefit label.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: identityAuthorities,
      validatorIds: ["nonempty_text", "not_generic_benefit_label"],
      blockerCode: `${benefit.toUpperCase()}_PLAN_NAME_MISSING`,
      renderPolicy: "render",
    }),
    requirement({
      id: `${benefit}.identity.carrierOrAdministrator`,
      path: `${root}.identity.carrierOrAdministrator`,
      label: `${title} carrier or administrator`,
      description:
        "Carrier for insured coverage or the responsible administrator/TPA for self-funded coverage.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: identityAuthorities,
      validatorIds: ["nonempty_text"],
      blockerCode: `${benefit.toUpperCase()}_CARRIER_OR_ADMINISTRATOR_MISSING`,
      renderPolicy: "render",
    }),
    requirement({
      id: `${benefit}.identity.planOrOptionId`,
      path: `${root}.identity.planOrOptionId`,
      label: `${title} plan or option identifier`,
      description:
        "Contract, plan, group, or option identifier used to distinguish choices and join design terms to rates.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "optional",
      },
      when: {
        op: "any",
        predicates: [
          fieldEquals(`${root}.identity.requiresOptionDisambiguation`, true),
          fieldEquals(`${root}.rates.requiresPlanJoin`, true),
        ],
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: identityAuthorities,
      validatorIds: ["nonempty_text"],
      blockerCode: `${benefit.toUpperCase()}_OPTION_ID_REQUIRED`,
      renderPolicy: "omit_when_absent",
    }),
    requirement({
      id: `${benefit}.identity.coveragePeriod`,
      path: `${root}.identity.coveragePeriod`,
      label: `${title} coverage period`,
      description: "Current benefit period with beginning and ending dates or a source-supported open-ended start date.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: employerPlanAuthorities,
      validatorIds: ["valid_date_interval", "overlaps_booklet_plan_year"],
      blockerCode: `${benefit.toUpperCase()}_COVERAGE_PERIOD_MISSING`,
      renderPolicy: "render",
    }),
    requirement({
      id: `${benefit}.identity.planDesign`,
      path: `${root}.identity.planDesign`,
      label: `${title} plan design`,
      description: "Source-specific design such as PPO, HMO, EPO, POS, indemnity, or DHMO.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planDesignAuthorities,
      validatorIds: ["recognized_plan_design_or_source_term"],
      blockerCode: `${benefit.toUpperCase()}_PLAN_DESIGN_MISSING`,
      renderPolicy: "render",
    }),
    requirement({
      id: `${benefit}.identity.serviceArea`,
      path: `${root}.identity.serviceArea`,
      label: `${title} service area`,
      description: "Geographic eligibility or service area for a regional or network-restricted plan.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "conditional",
      },
      when: {
        op: "any",
        predicates: [
          fieldEquals(`${root}.identity.isRegional`, true),
          fieldIn(`${root}.identity.planDesign`, ["HMO", "DHMO"]),
        ],
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planDesignAuthorities,
      validatorIds: ["nonempty_service_area"],
      blockerCode: `${benefit.toUpperCase()}_SERVICE_AREA_MISSING`,
      renderPolicy: "render",
    }),
    requirement({
      id: `${benefit}.rates.employeeCost`,
      path: `${root}.rates.employeeCost`,
      label: `${title} employee cost`,
      description:
        "Employee cost for every offered coverage tier when the artifact is an enrollment booklet and costs are not expressly provided elsewhere.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "optional",
      },
      when: {
        op: "all",
        predicates: [
          fieldEquals("booklet.mode", "enrollment"),
          {
            op: "not",
            predicate: fieldEquals(`${root}.rates.providedSeparately`, true),
          },
        ],
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: ["rate_or_contribution", "employer_selection", "manual_answer"],
      acceptedExplicitNoneReasons: ["EMPLOYER_PAYS_FULL_COST", "NO_EMPLOYEE_PREMIUM"],
      validatorIds: ["complete_coverage_tier_schedule", "nonnegative_money"],
      blockerCode: `${benefit.toUpperCase()}_EMPLOYEE_COST_MISSING`,
      renderPolicy: "render",
    }),
    requirement({
      id: `${benefit}.rates.payFrequency`,
      path: `${root}.rates.payFrequency`,
      label: `${title} payroll frequency`,
      description: "Payroll deduction frequency whenever a per-pay-period value is shown.",
      levels: {
        complete_extraction: "conditional",
        safe_booklet: "conditional",
        formal_disclosure: "optional",
      },
      when: fieldEquals(`${root}.rates.includesPerPayAmounts`, true),
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: ["rate_or_contribution", "employer_selection", "manual_answer"],
      validatorIds: ["recognized_pay_frequency"],
      blockerCode: `${benefit.toUpperCase()}_PAY_FREQUENCY_MISSING`,
      renderPolicy: "render",
    }),
    requirement({
      id: `${benefit}.contacts.memberServices`,
      path: `${root}.contacts.memberServices`,
      label: `${title} member-services contact`,
      description: "Current plan-specific phone number or website for benefit questions.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: contactAuthorities,
      validatorIds: ["valid_contact_channel"],
      blockerCode: `${benefit.toUpperCase()}_MEMBER_CONTACT_MISSING`,
      renderPolicy: "render",
    }),
    requirement({
      id: `${benefit}.documents.governingTerms`,
      path: `${root}.documents.governingTerms`,
      label: `${title} governing terms`,
      description: "Current certificate, EOC, SPD, SBC, schedule, or plan-document reference controlling the summarized terms.",
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: ["current_plan_document", "current_amendment_or_rider", "manual_answer"],
      validatorIds: ["current_effective_document", "matches_selected_option"],
      blockerCode: `${benefit.toUpperCase()}_GOVERNING_DOCUMENT_MISSING`,
      renderPolicy: "reference_governing_document",
    }),
    requirement({
      id: `${benefit}.formal.eligibilityAndLossRules`,
      path: `${root}.formal.eligibilityAndLossRules`,
      label: `${title} eligibility and loss-of-benefit rules`,
      description:
        "Conditions for eligibility and circumstances causing denial, loss, forfeiture, suspension, reduction, or recovery; required only for an applicable formal disclosure workflow.",
      levels: { formal_disclosure: "required" },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: legalAuthorities,
      validatorIds: ["formal_terms_complete"],
      blockerCode: `${benefit.toUpperCase()}_FORMAL_ELIGIBILITY_TERMS_MISSING`,
      renderPolicy: "never_render",
    }),
    requirement({
      id: `${benefit}.formal.claimsAndAppeals`,
      path: `${root}.formal.claimsAndAppeals`,
      label: `${title} claims and appeals procedure`,
      description:
        "Claims, review, timing, and remedy terms for an applicable SPD or other formal disclosure; a safe booklet may instead reference the governing document.",
      levels: {
        complete_extraction: "optional",
        safe_booklet: "optional",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: legalAuthorities,
      validatorIds: ["formal_claims_procedure_complete"],
      blockerCode: `${benefit.toUpperCase()}_FORMAL_CLAIMS_PROCEDURE_MISSING`,
      renderPolicy: "never_render",
    }),
  ];
}

const medicalSpecificFields: BenefitFieldRequirement[] = [
  requirement({
    id: "medical.coverage.coverageFor",
    path: "plans.medical.coverage.coverageFor",
    label: "Medical coverage population",
    description: "Coverage population or tier terminology used by the current plan source.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: employerPlanAuthorities,
    validatorIds: ["recognized_coverage_population"],
    blockerCode: "MEDICAL_COVERAGE_FOR_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.network.usesNetwork",
    path: "plans.medical.network.usesNetwork",
    label: "Medical network use",
    description: "Explicit yes/no statement of whether the plan uses a provider network.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["boolean_value"],
    blockerCode: "MEDICAL_NETWORK_STATUS_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.network.tiers",
    path: "plans.medical.network.tiers",
    label: "Medical network tiers",
    description: "Every applicable provider tier, preserving source terminology and least-to-most-cost ordering.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "conditional",
      formal_disclosure: "conditional",
    },
    when: fieldEquals("plans.medical.network.usesNetwork", true),
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["nonempty_network_tiers", "unique_network_tier_ids"],
    blockerCode: "MEDICAL_NETWORK_TIERS_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.network.outOfNetworkStatus",
    path: "plans.medical.network.outOfNetworkStatus",
    label: "Medical out-of-network status",
    description: "Covered, emergency-only, or not-covered status for out-of-network care.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedNotApplicableReasons: ["PLAN_HAS_NO_PROVIDER_NETWORK"],
    validatorIds: ["medical_out_of_network_status"],
    blockerCode: "MEDICAL_OUT_OF_NETWORK_STATUS_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.network.providerDirectory",
    path: "plans.medical.network.providerDirectory",
    label: "Medical provider directory",
    description: "Direct plan-specific directory URL or phone number.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "conditional",
      formal_disclosure: "conditional",
    },
    when: fieldEquals("plans.medical.network.usesNetwork", true),
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: contactAuthorities,
    validatorIds: ["valid_contact_channel", "plan_specific_directory"],
    blockerCode: "MEDICAL_PROVIDER_DIRECTORY_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.network.referralRule",
    path: "plans.medical.network.referralRule",
    label: "Medical specialist referral rule",
    description: "Explicit referral-required status and material scope or exceptions.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["NO_REFERRAL_REQUIRED"],
    validatorIds: ["referral_rule_complete"],
    blockerCode: "MEDICAL_REFERRAL_RULE_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.financial.deductible",
    path: "plans.medical.financial.deductible",
    label: "Medical deductible",
    description: "Individual/family deductible by network tier, benefit period, and family accumulation rule.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["NO_OVERALL_DEDUCTIBLE"],
    validatorIds: ["nonnegative_money", "network_tiers_complete", "family_deductible_rule_complete"],
    blockerCode: "MEDICAL_DEDUCTIBLE_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.financial.servicesBeforeDeductible",
    path: "plans.medical.financial.servicesBeforeDeductible",
    label: "Services before deductible",
    description: "Explicit yes/no answer and the applicable service categories when any are covered before the deductible.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["NO_SERVICES_BEFORE_DEDUCTIBLE"],
    validatorIds: ["pre_deductible_services_complete"],
    blockerCode: "MEDICAL_PRE_DEDUCTIBLE_SERVICES_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.financial.specificDeductibles",
    path: "plans.medical.financial.specificDeductibles",
    label: "Medical service-specific deductibles",
    description: "Every service-specific deductible or explicit confirmation that none apply.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["NO_SERVICE_SPECIFIC_DEDUCTIBLES"],
    validatorIds: ["specific_deductibles_complete"],
    blockerCode: "MEDICAL_SPECIFIC_DEDUCTIBLES_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.financial.outOfPocketLimit",
    path: "plans.medical.financial.outOfPocketLimit",
    label: "Medical out-of-pocket limit",
    description: "Individual/family out-of-pocket limit by network tier, period, and accumulation rule.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedNotApplicableReasons: ["PLAN_HAS_NO_OUT_OF_POCKET_LIMIT"],
    validatorIds: ["nonnegative_money", "network_tiers_complete", "family_out_of_pocket_rule_complete"],
    blockerCode: "MEDICAL_OUT_OF_POCKET_LIMIT_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.financial.excludedFromOutOfPocket",
    path: "plans.medical.financial.excludedFromOutOfPocket",
    label: "Medical out-of-pocket exclusions",
    description: "Expenses expressly excluded from the out-of-pocket limit.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["NO_ADDITIONAL_OUT_OF_POCKET_EXCLUSIONS"],
    validatorIds: ["out_of_pocket_exclusions_complete"],
    blockerCode: "MEDICAL_OUT_OF_POCKET_EXCLUSIONS_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.services.commonEventSchedule",
    path: "plans.medical.services.commonEventSchedule",
    label: "Medical common-event service schedule",
    description:
      "Canonical common-event rows with coverage state and plan-specific service identity. Complete extraction/formal disclosure cover the federal SBC rows; the booklet may render a selected sourced subset.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "optional",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["medical_common_event_keys_complete", "service_coverage_state_complete"],
    blockerCode: "MEDICAL_COMMON_EVENT_SCHEDULE_INCOMPLETE",
    renderPolicy: "omit_when_absent",
  }),
  requirement({
    id: "medical.services.coreBookletSchedule",
    path: "plans.medical.services.coreBookletSchedule",
    label: "Medical core booklet service schedule",
    description:
      "Booklet comparison rows for primary care, specialist, preventive, urgent, emergency, hospital, mental health, and prescription coverage.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "optional",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["medical_core_booklet_services_complete", "service_cells_complete"],
    blockerCode: "MEDICAL_CORE_SERVICE_SCHEDULE_INCOMPLETE",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.services.costSharingCells",
    path: "plans.medical.services.costSharingCells",
    label: "Medical service cost-sharing cells",
    description: "Cost sharing for every covered service and every applicable network tier.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["service_cells_complete", "cost_share_value_valid", "network_tiers_complete"],
    blockerCode: "MEDICAL_SERVICE_COST_SHARING_INCOMPLETE",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.services.qualifiers",
    path: "plans.medical.services.qualifiers",
    label: "Medical service qualifiers",
    description:
      "Per-service deductible applicability, limits, exceptions, preauthorization, penalties, visit/unit limits, and age rules where applicable.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["NO_MATERIAL_SERVICE_QUALIFIERS"],
    validatorIds: ["service_qualifiers_complete", "preauthorization_penalty_preserved"],
    blockerCode: "MEDICAL_SERVICE_QUALIFIERS_INCOMPLETE",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.prescriptions.formularyContact",
    path: "plans.medical.prescriptions.formularyContact",
    label: "Medical formulary resource",
    description: "Plan-specific formulary URL or prescription-benefit contact.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "conditional",
      formal_disclosure: "conditional",
    },
    when: fieldEquals("plans.medical.prescriptions.covered", true),
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: contactAuthorities,
    validatorIds: ["valid_contact_channel", "plan_specific_formulary"],
    blockerCode: "MEDICAL_FORMULARY_RESOURCE_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.prescriptions.tierSchedule",
    path: "plans.medical.prescriptions.tierSchedule",
    label: "Medical prescription tier schedule",
    description: "Carrier tier names, normalized semantics, retail/mail-order cost sharing where applicable, and material pharmacy rules.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["PRESCRIPTION_COVERAGE_NOT_INCLUDED"],
    validatorIds: ["prescription_tiers_complete", "retail_mail_order_qualifiers_complete"],
    blockerCode: "MEDICAL_PRESCRIPTION_SCHEDULE_INCOMPLETE",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.compatibility.hsaEligible",
    path: "plans.medical.compatibility.hsaEligible",
    label: "Medical HSA compatibility designation",
    description:
      "Explicit source-backed plan designation when the option is presented as HDHP/HSA-compatible or paired with an employer HSA; deductible arithmetic alone is insufficient.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "conditional",
      formal_disclosure: "optional",
    },
    when: {
      op: "any",
      predicates: [
        fieldEquals("plans.medical.compatibility.marketedAsHsaCompatible", true),
        fieldEquals("offerings.hsa.offered", true),
      ],
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: ["current_plan_document", "current_amendment_or_rider", "employer_selection", "manual_answer"],
    validatorIds: ["not_inferred_from_deductible", "linked_hsa_plan_match"],
    blockerCode: "MEDICAL_HSA_COMPATIBILITY_UNCONFIRMED",
    renderPolicy: "render",
  }),
  requirement({
    id: "medical.coverage.exclusionsAndOtherServices",
    path: "plans.medical.coverage.exclusionsAndOtherServices",
    label: "Medical exclusions and other covered services",
    description: "Source-listed exclusions and other covered services with material limits.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "optional",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["source_list_preserved", "material_limits_preserved"],
    blockerCode: "MEDICAL_EXCLUSIONS_OR_OTHER_SERVICES_MISSING",
    renderPolicy: "omit_when_absent",
  }),
  requirement({
    id: "medical.formal.coverageExamples",
    path: "plans.medical.formal.coverageExamples",
    label: "Medical SBC coverage examples",
    description: "Current standardized coverage examples when the formal artifact is an SBC; not recalculated for an ordinary booklet.",
    levels: {
      complete_extraction: "optional",
      safe_booklet: "optional",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: legalAuthorities,
    validatorIds: ["coverage_examples_current", "coverage_example_assumptions_preserved"],
    blockerCode: "MEDICAL_FORMAL_COVERAGE_EXAMPLES_MISSING",
    renderPolicy: "never_render",
  }),
];

const dentalSpecificFields: BenefitFieldRequirement[] = [
  requirement({
    id: "dental.financial.benefitPeriod",
    path: "plans.dental.financial.benefitPeriod",
    label: "Dental benefit period",
    description: "Calendar, contract, or other reset period for deductibles, limits, and frequencies.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["recognized_benefit_period"],
    blockerCode: "DENTAL_BENEFIT_PERIOD_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "dental.network.usesNetwork",
    path: "plans.dental.network.usesNetwork",
    label: "Dental network use",
    description: "Explicit yes/no network status and network name when applicable.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["network_status_and_name_complete"],
    blockerCode: "DENTAL_NETWORK_STATUS_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "dental.network.providerDirectory",
    path: "plans.dental.network.providerDirectory",
    label: "Dental provider directory",
    description: "Plan-specific directory URL or phone number.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "conditional",
      formal_disclosure: "conditional",
    },
    when: fieldEquals("plans.dental.network.usesNetwork", true),
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: contactAuthorities,
    validatorIds: ["valid_contact_channel", "plan_specific_directory"],
    blockerCode: "DENTAL_PROVIDER_DIRECTORY_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "dental.financial.deductible",
    path: "plans.dental.financial.deductible",
    label: "Dental deductible",
    description: "Per-person/family deductible by class and network tier, including explicit zero/no-deductible treatment.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["NO_DENTAL_DEDUCTIBLE"],
    acceptedNotApplicableReasons: ["DHMO_USES_COPAY_SCHEDULE"],
    validatorIds: ["dental_deductible_classes_complete", "nonnegative_money"],
    blockerCode: "DENTAL_DEDUCTIBLE_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "dental.financial.annualMaximum",
    path: "plans.dental.financial.annualMaximum",
    label: "Dental annual maximum",
    description: "Per-person annual maximum by network/class where different, or explicit unlimited/not-applicable treatment.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["UNLIMITED_DENTAL_ANNUAL_MAXIMUM"],
    acceptedNotApplicableReasons: ["DHMO_HAS_NO_ANNUAL_MAXIMUM_CONCEPT"],
    validatorIds: ["dental_annual_maximum_complete", "separate_from_orthodontic_maximum"],
    blockerCode: "DENTAL_ANNUAL_MAXIMUM_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "dental.financial.waitingPeriods",
    path: "plans.dental.financial.waitingPeriods",
    label: "Dental waiting periods",
    description: "Explicit none or each service-specific waiting period and affected class.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["NO_DENTAL_WAITING_PERIODS"],
    validatorIds: ["waiting_period_scope_complete"],
    blockerCode: "DENTAL_WAITING_PERIODS_UNRESOLVED",
    renderPolicy: "render",
  }),
  ...(["preventive", "basic", "major"] as const).map((category) =>
    requirement({
      id: `dental.services.${category}`,
      path: `plans.dental.services.${category}`,
      label: `Dental ${category} coverage`,
      description: `Coverage state, source class name, normalized category, representative services, and member cost for ${category} care.`,
      levels: {
        complete_extraction: "required",
        safe_booklet: "required",
        formal_disclosure: "required",
      },
      material: true,
      evidenceRequired: true,
      acceptedAuthorities: planDesignAuthorities,
      validatorIds: ["dental_service_category_complete", "member_vs_plan_percentage_unambiguous"],
      blockerCode: `DENTAL_${category.toUpperCase()}_COVERAGE_MISSING`,
      renderPolicy: "render",
    }),
  ),
  requirement({
    id: "dental.services.frequencyLimits",
    path: "plans.dental.services.frequencyLimits",
    label: "Dental service frequency limits",
    description:
      "Material source-stated intervals for exams, cleanings, x-rays, replacements, crowns/dentures, implants, and other high-impact services.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["NO_MATERIAL_DENTAL_FREQUENCY_LIMITS"],
    validatorIds: ["frequency_interval_qualified", "service_scope_qualified"],
    blockerCode: "DENTAL_FREQUENCY_LIMITS_INCOMPLETE",
    renderPolicy: "render",
  }),
  requirement({
    id: "dental.services.materialExclusions",
    path: "plans.dental.services.materialExclusions",
    label: "Dental material exclusions",
    description: "Material exclusions, replacement rules, missing-tooth provisions, and alternate-benefit rules stated by the source.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "optional",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["NO_MATERIAL_DENTAL_EXCLUSIONS_IDENTIFIED"],
    validatorIds: ["material_exclusions_preserved"],
    blockerCode: "DENTAL_MATERIAL_EXCLUSIONS_MISSING",
    renderPolicy: "omit_when_absent",
  }),
  requirement({
    id: "dental.orthodontia.status",
    path: "plans.dental.orthodontia.status",
    label: "Dental orthodontia status",
    description: "Adult-and-child, child-only, restricted, or not-covered status.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["orthodontia_status_recognized"],
    blockerCode: "DENTAL_ORTHODONTIA_STATUS_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "dental.orthodontia.schedule",
    path: "plans.dental.orthodontia.schedule",
    label: "Dental orthodontia schedule",
    description: "Population eligibility, member cost, lifetime maximum/payment model, waiting period, and in-progress treatment rule.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "conditional",
      formal_disclosure: "conditional",
    },
    when: fieldIn("plans.dental.orthodontia.status", [
      "coveredAdultAndChild",
      "coveredChildOnly",
      "coveredOtherRestriction",
    ]),
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["orthodontia_population_complete", "orthodontia_maximum_separate", "orthodontia_qualifiers_complete"],
    blockerCode: "DENTAL_ORTHODONTIA_SCHEDULE_INCOMPLETE",
    renderPolicy: "render",
  }),
  requirement({
    id: "dental.ppo.outOfNetworkSchedule",
    path: "plans.dental.ppo.outOfNetworkSchedule",
    label: "Dental out-of-network schedule",
    description: "Out-of-network deductible, class benefits/member shares, plan-allowance basis, and excess-charge exposure.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "conditional",
      formal_disclosure: "conditional",
    },
    when: {
      op: "all",
      predicates: [
        fieldIn("plans.dental.identity.planDesign", ["PPO", "indemnity"]),
        fieldEquals("plans.dental.network.outOfNetworkCovered", true),
      ],
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedNotApplicableReasons: ["DENTAL_OUT_OF_NETWORK_NOT_COVERED", "PLAN_HAS_NO_PROVIDER_NETWORK"],
    validatorIds: ["dental_out_of_network_classes_complete", "above_allowance_exposure_separate"],
    blockerCode: "DENTAL_OUT_OF_NETWORK_SCHEDULE_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "dental.dhmo.copaySchedule",
    path: "plans.dental.dhmo.copaySchedule",
    label: "DHMO copay schedule",
    description: "Governing schedule and material procedure copays for a DHMO design.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "conditional",
      formal_disclosure: "conditional",
    },
    when: fieldEquals("plans.dental.identity.planDesign", "DHMO"),
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["dhmo_copay_schedule_current", "material_dhmo_services_complete"],
    blockerCode: "DENTAL_DHMO_COPAY_SCHEDULE_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "dental.dhmo.primaryDentistAndReferralRules",
    path: "plans.dental.dhmo.primaryDentistAndReferralRules",
    label: "DHMO primary-dentist and referral rules",
    description: "Dentist selection/change and specialist referral rules where the DHMO requires them.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "conditional",
      formal_disclosure: "conditional",
    },
    when: fieldEquals("plans.dental.dhmo.requiresPrimaryDentist", true),
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["primary_dentist_rules_complete"],
    blockerCode: "DENTAL_DHMO_PRIMARY_DENTIST_RULES_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "dental.pretreatmentRule",
    path: "plans.dental.pretreatmentRule",
    label: "Dental pretreatment rule",
    description: "Required, recommended, or not-applicable status and any stated threshold.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "optional",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedNotApplicableReasons: ["NO_DENTAL_PRETREATMENT_PROCESS"],
    acceptedExplicitNoneReasons: ["PRETREATMENT_NOT_REQUIRED_OR_RECOMMENDED"],
    validatorIds: ["pretreatment_rule_qualified"],
    blockerCode: "DENTAL_PRETREATMENT_RULE_MISSING",
    renderPolicy: "omit_when_absent",
  }),
];

const visionSpecificFields: BenefitFieldRequirement[] = [
  requirement({
    id: "vision.financial.benefitPeriod",
    path: "plans.vision.financial.benefitPeriod",
    label: "Vision benefit period",
    description: "Calendar, contract, or rolling reset period for vision benefits.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["recognized_benefit_period"],
    blockerCode: "VISION_BENEFIT_PERIOD_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "vision.network.usesNetwork",
    path: "plans.vision.network.usesNetwork",
    label: "Vision network use",
    description: "Explicit network status, design, and network name when applicable.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["network_status_and_name_complete"],
    blockerCode: "VISION_NETWORK_STATUS_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "vision.network.providerDirectory",
    path: "plans.vision.network.providerDirectory",
    label: "Vision provider directory",
    description: "Plan-specific provider-directory URL or phone number.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "conditional",
      formal_disclosure: "conditional",
    },
    when: fieldEquals("plans.vision.network.usesNetwork", true),
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: contactAuthorities,
    validatorIds: ["valid_contact_channel", "plan_specific_directory"],
    blockerCode: "VISION_PROVIDER_DIRECTORY_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "vision.exam.schedule",
    path: "plans.vision.exam.schedule",
    label: "Vision exam schedule",
    description: "Coverage state, member cost, exact frequency, network tier, and age/population qualifiers.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["vision_schedule_complete", "frequency_interval_qualified"],
    blockerCode: "VISION_EXAM_SCHEDULE_INCOMPLETE",
    renderPolicy: "render",
  }),
  requirement({
    id: "vision.materials.copay",
    path: "plans.vision.materials.copay",
    label: "Vision materials copay",
    description: "Amount and scope, including whether one copay applies to lenses and frames together.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["NO_VISION_MATERIALS_COPAY"],
    validatorIds: ["materials_copay_scope_complete", "nonnegative_money"],
    blockerCode: "VISION_MATERIALS_COPAY_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "vision.lenses.standardSchedule",
    path: "plans.vision.lenses.standardSchedule",
    label: "Vision standard-lens schedule",
    description: "Covered standard lens types, member cost, frequency, and network/population qualifiers.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["standard_lens_types_complete", "vision_schedule_complete", "frequency_interval_qualified"],
    blockerCode: "VISION_STANDARD_LENS_SCHEDULE_INCOMPLETE",
    renderPolicy: "render",
  }),
  requirement({
    id: "vision.frames.schedule",
    path: "plans.vision.frames.schedule",
    label: "Vision frame schedule",
    description: "Allowance or covered-in-full rule, member overage, exact frequency, network, and retailer/frame-collection qualifiers.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["vision_schedule_complete", "frequency_interval_qualified", "retailer_allowance_variants_preserved", "covered_in_full_not_allowance"],
    blockerCode: "VISION_FRAME_SCHEDULE_INCOMPLETE",
    renderPolicy: "render",
  }),
  requirement({
    id: "vision.contacts.electiveSchedule",
    path: "plans.vision.contacts.electiveSchedule",
    label: "Vision elective-contact schedule",
    description: "Coverage/allowance, fitting treatment, frequency, and whether contacts replace or supplement eyeglasses.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "required",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["ELECTIVE_CONTACTS_NOT_COVERED"],
    validatorIds: ["vision_schedule_complete", "frequency_interval_qualified", "contacts_substitution_rule_complete"],
    blockerCode: "VISION_ELECTIVE_CONTACT_SCHEDULE_INCOMPLETE",
    renderPolicy: "render",
  }),
  requirement({
    id: "vision.contacts.necessarySchedule",
    path: "plans.vision.contacts.necessarySchedule",
    label: "Vision necessary-contact schedule",
    description: "Eligibility criteria, member cost or allowance, frequency, and authorization rule for medically necessary contacts.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "conditional",
      formal_disclosure: "conditional",
    },
    when: fieldEquals("plans.vision.contacts.necessaryCovered", true),
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["necessary_contact_criteria_complete", "vision_schedule_complete"],
    blockerCode: "VISION_NECESSARY_CONTACT_SCHEDULE_INCOMPLETE",
    renderPolicy: "render",
  }),
  requirement({
    id: "vision.network.outOfNetworkSchedule",
    path: "plans.vision.network.outOfNetworkSchedule",
    label: "Vision out-of-network reimbursement schedule",
    description: "Reimbursement for exam, each lens class, frames, elective contacts, and necessary contacts where applicable.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "conditional",
      formal_disclosure: "conditional",
    },
    when: fieldEquals("plans.vision.network.outOfNetworkCovered", true),
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedNotApplicableReasons: ["VISION_OUT_OF_NETWORK_NOT_COVERED", "PLAN_HAS_NO_PROVIDER_NETWORK"],
    validatorIds: ["vision_out_of_network_core_services_complete", "reimbursement_not_covered_in_full"],
    blockerCode: "VISION_OUT_OF_NETWORK_REIMBURSEMENT_MISSING",
    renderPolicy: "render",
  }),
  requirement({
    id: "vision.lenses.enhancements",
    path: "plans.vision.lenses.enhancements",
    label: "Vision lens enhancements",
    description: "Member prices and qualifiers for promoted lens enhancements.",
    levels: {
      complete_extraction: "optional",
      safe_booklet: "conditional",
      formal_disclosure: "optional",
    },
    when: fieldEquals("plans.vision.lenses.enhancementsPromoted", true),
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["promoted_enhancements_sourced", "discount_vs_insured_benefit_labeled"],
    blockerCode: "VISION_PROMOTED_ENHANCEMENTS_UNSOURCED",
    renderPolicy: "omit_when_absent",
  }),
  requirement({
    id: "vision.lowVision.schedule",
    path: "plans.vision.lowVision.schedule",
    label: "Low-vision benefit schedule",
    description: "Services, maximum, frequency, network restriction, and preauthorization when low-vision coverage exists.",
    levels: {
      complete_extraction: "conditional",
      safe_booklet: "optional",
      formal_disclosure: "conditional",
    },
    when: fieldEquals("plans.vision.lowVision.covered", true),
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    validatorIds: ["low_vision_schedule_complete"],
    blockerCode: "VISION_LOW_VISION_SCHEDULE_INCOMPLETE",
    renderPolicy: "omit_when_absent",
  }),
  requirement({
    id: "vision.services.materialExclusions",
    path: "plans.vision.services.materialExclusions",
    label: "Vision material exclusions",
    description: "Replacement, loss/damage, nonprescription, and other material source-stated exclusions.",
    levels: {
      complete_extraction: "required",
      safe_booklet: "optional",
      formal_disclosure: "required",
    },
    material: true,
    evidenceRequired: true,
    acceptedAuthorities: planDesignAuthorities,
    acceptedExplicitNoneReasons: ["NO_MATERIAL_VISION_EXCLUSIONS_IDENTIFIED"],
    validatorIds: ["material_exclusions_preserved"],
    blockerCode: "VISION_MATERIAL_EXCLUSIONS_MISSING",
    renderPolicy: "omit_when_absent",
  }),
];

export const medicalRequirements: BenefitRequirementDefinition = {
  benefitType: "medical",
  title: "Medical plan requirements",
  entityKind: "plan",
  fields: [...commonPlanFields("medical"), ...medicalSpecificFields],
  invariants: [
    {
      id: "medical.material_claims_have_field_evidence",
      description: "Every rendered material medical value has field-level evidence effective for the booklet plan year.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "medical.service_cells_are_complete",
      description: "Every covered/rendered service has cost sharing for each applicable network tier plus deductible, limit, exception, and preauthorization qualifiers.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "medical.not_covered_has_no_plan_payment",
      description: "A not-covered service cannot simultaneously carry a positive plan payment or member copay.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "medical.family_accumulators_are_qualified",
      description: "Family deductible and out-of-pocket values identify embedded/non-embedded accumulation whenever family coverage is offered.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "medical.out_of_network_branch_is_consistent",
      description: "Out-of-network cells are omitted/not-applicable only when source-backed network rules make them inapplicable.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "medical.pediatric_rows_do_not_activate_standalone_benefits",
      description: "Pediatric dental/vision rows in a medical source never activate standalone dental or vision offerings.",
      gates: ["complete_extraction", "safe_booklet"],
    },
    {
      id: "medical.hsa_compatibility_is_not_inferred",
      description: "HSA compatibility is never inferred solely from a deductible, plan name, or HDHP-like arithmetic.",
      gates: ["complete_extraction", "safe_booklet"],
    },
    {
      id: "medical.formal_is_separate",
      description: "Passing safe_booklet does not assert SBC/SPD completeness or delivery compliance.",
      gates: ["safe_booklet", "formal_disclosure"],
    },
  ],
  researchSources: [
    {
      title: "CMS Summary of Benefits and Coverage template",
      url: "https://www.cms.gov/CCIIO/Resources/Forms-Reports-and-Other-Resources/Downloads/SBC-Template-Accessible-Format-11-2019.pdf",
      authority: "federal",
    },
    {
      title: "CMS instructions for completing the SBC for group coverage",
      url: "https://www.cms.gov/files/document/group-instructions-060723.pdf",
      authority: "federal",
    },
    {
      title: "DOL plan information and disclosure overview",
      url: "https://www.dol.gov/general/topic/health-plans/planinformation",
      authority: "federal",
    },
  ],
  formalDisclosureRequiresSeparateApplicability: true,
};

export const dentalRequirements: BenefitRequirementDefinition = {
  benefitType: "dental",
  title: "Dental plan requirements",
  entityKind: "plan",
  fields: [...commonPlanFields("dental"), ...dentalSpecificFields],
  invariants: [
    {
      id: "dental.material_claims_have_field_evidence",
      description: "Every rendered dental amount, percentage, frequency, limit, and coverage state has current field-level evidence.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "dental.service_classes_preserve_source_semantics",
      description: "Carrier class names and normalized service categories are stored separately; Class A/B/C meanings are never assumed across carriers.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "dental.member_and_plan_percentages_not_swapped",
      description: "Every percentage identifies whether it is the member share or the plan share.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "dental.orthodontic_and_annual_maxima_are_separate",
      description: "The non-orthodontic annual maximum and orthodontic lifetime maximum are never collapsed.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "dental.dhmo_uses_schedule_model",
      description: "A DHMO copay schedule is not forced into PPO percentage-class fields; unsupported deductible/max concepts use source-backed not-applicable states.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "dental.out_of_network_exposure_is_separate",
      description: "Out-of-network class percentage and member liability above the plan allowance remain separate facts.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "dental.silence_is_not_none",
      description: "Source silence never establishes no waiting period, no deductible, unlimited benefits, or no exclusions.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "dental.formal_is_separate",
      description: "Standalone dental may be an excepted benefit; passing safe_booklet does not assert SBC applicability or SPD delivery compliance.",
      gates: ["safe_booklet", "formal_disclosure"],
    },
  ],
  researchSources: [
    {
      title: "OPM FEDVIP plan-benefit public-use file definitions",
      url: "https://www.opm.gov/healthcare-insurance/healthcare/transparency-in-healthcare/public-use-files/",
      authority: "official_program",
    },
    {
      title: "2026 OPM MetLife Federal Dental Plan official brochure",
      url: "https://www.opm.gov/healthcare-insurance/healthcare/plan-information/plans/pdf/2026/brochures/02AP-11.pdf",
      authority: "official_plan",
    },
    {
      title: "DOL FAQ on limited-scope dental and vision excepted benefits",
      url: "https://www.dol.gov/node/25144",
      authority: "federal",
    },
    {
      title: "IRS SBC final-rule discussion of standalone dental and vision",
      url: "https://www.irs.gov/irb/2012-15_IRB",
      authority: "federal",
    },
  ],
  formalDisclosureRequiresSeparateApplicability: true,
};

export const visionRequirements: BenefitRequirementDefinition = {
  benefitType: "vision",
  title: "Vision plan requirements",
  entityKind: "plan",
  fields: [...commonPlanFields("vision"), ...visionSpecificFields],
  invariants: [
    {
      id: "vision.material_claims_have_field_evidence",
      description: "Every rendered copay, allowance, reimbursement, frequency, and feature has current field-level evidence.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "vision.core_schedules_have_qualifiers",
      description: "Exam, lenses, frames, and contacts identify cost/allowance, exact interval, network, and applicable age/retailer/population qualifiers.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "vision.contacts_substitution_is_preserved",
      description: "Contacts are never presented in addition to eyeglasses when the source makes them an alternative benefit.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "vision.covered_in_full_is_not_allowance",
      description: "Covered-in-full treatment remains distinct from a dollar allowance or reimbursement ceiling.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "vision.retailer_allowances_are_not_collapsed",
      description: "Material retailer/frame-collection allowance variants are preserved and the highest value is not generalized.",
      gates: ["complete_extraction", "safe_booklet", "formal_disclosure"],
    },
    {
      id: "vision.discount_features_are_labeled",
      description: "Discounts and non-insured features are not described as insured benefits.",
      gates: ["complete_extraction", "safe_booklet"],
    },
    {
      id: "vision.formal_is_separate",
      description: "Standalone vision may be an excepted benefit; passing safe_booklet does not assert SBC applicability or SPD delivery compliance.",
      gates: ["safe_booklet", "formal_disclosure"],
    },
  ],
  researchSources: [
    {
      title: "OPM FEDVIP plan-benefit public-use file definitions",
      url: "https://www.opm.gov/healthcare-insurance/healthcare/transparency-in-healthcare/public-use-files/",
      authority: "official_program",
    },
    {
      title: "2026 OPM MetLife Federal Vision Plan official brochure",
      url: "https://www.opm.gov/healthcare-insurance/healthcare/plan-information/plans/BrochureJson?brochureNumber=02AP-12&year=2026",
      authority: "official_plan",
    },
    {
      title: "DOL FAQ on limited-scope dental and vision excepted benefits",
      url: "https://www.dol.gov/node/25144",
      authority: "federal",
    },
    {
      title: "IRS SBC final-rule discussion of standalone dental and vision",
      url: "https://www.irs.gov/irb/2012-15_IRB",
      authority: "federal",
    },
  ],
  formalDisclosureRequiresSeparateApplicability: true,
};
