export const parsingStages = [
  "Uploaded",
  "Classifying",
  "Extracting",
  "Matched",
  "Applied to booklet",
];

export const phaseDefinitions = [
  {
    id: "employer",
    number: "01",
    icon: "building",
    title: "Employer setup",
    description: "Upload the employer’s group information form.",
    accepted: "New Group Application or Annual Group Information Form",
    fileName: "Big Tows employer application.pdf",
    fileMeta: "Application · 1.8 MB",
    steps: [
      "Reading employer documents and website…",
      "Finding company information…",
      "Detecting plan year and eligibility rules…",
      "Matching contacts and public details…",
      "Company profile ready for review.",
    ],
    facts: [
      ["Employer", "Big Tows, Inc."],
      ["Plan year", "Mar 1, 2026 – Feb 28, 2027"],
      ["Eligibility", "First of month after 30 days"],
      ["Enrollment contact", "Morgan Lee · People Operations"],
      ["Website", "bigtows.com"],
    ],
  },
  {
    id: "documents",
    number: "02",
    icon: "document",
    title: "Official plan documents",
    description: "All offered benefits—medical, dental, vision, life, disability, voluntary/PBO, and more.",
    accepted: "SBCs, SPDs, plan summaries, certificates, or carrier PDFs",
    fileName: "Excellus Bronze HSA SBC.pdf",
    fileMeta: "Benefits PDF · 2.4 MB",
    steps: [
      "Extracting plan text…",
      "Reading benefit tables…",
      "Finding deductible and OOP max…",
      "Finding copays and Rx tiers…",
      "Plan details ready.",
    ],
    facts: [
      ["Deductible", "$6,900 individual / $13,800 family"],
      ["Out-of-pocket max", "$7,500 individual / $15,000 family"],
      ["Primary care", "20% after deductible"],
      ["Plan type", "HSA-qualified · Bronze"],
    ],
  },
  {
    id: "rates",
    number: "03",
    icon: "sheet",
    title: "Rate source",
    description: "Tier rates, employer contributions, and payroll deductions.",
    accepted: "Rate sheet, broker export, or renewal file",
    fileName: "2026 renewal rates.xlsx",
    fileMeta: "Spreadsheet · 482 KB",
    steps: [
      "Reading workbook tabs…",
      "Normalizing tier names…",
      "Finding plan-rate rows…",
      "Matching rates to selected plans…",
      "Rates ready.",
    ],
    facts: [
      ["Carrier", "Excellus BCBS"],
      ["Medical plan", "Bronze HSA 6900"],
      ["Coverage tiers", "4 tiers normalized"],
      ["Contribution", "50% employee-only premium"],
    ],
  },
  {
    id: "instructions",
    number: "04",
    icon: "message",
    title: "Extra instructions",
    description: "Final decisions, corrections, and client-specific language.",
    accepted: "Typed note, copied email, or broker instruction",
    fileName: "Broker final decisions.txt",
    fileMeta: "Client note · 3 KB",
    steps: [
      "Reading instructions…",
      "Looking for final decisions…",
      "Applying overrides…",
      "Checking conflicts…",
      "Instructions applied.",
    ],
    facts: [
      ["Plan selection", "Bronze HSA 6900 confirmed"],
      ["Enrollment copy", "Use Employee Navigator"],
      ["Contact correction", "Morgan Lee confirmed"],
      ["Override priority", "Broker decision · final"],
    ],
  },
];

export const bookletPages = [
  { id: "cover", phase: "employer", number: 1, title: "Cover", kind: "cover" },
  { id: "welcome", phase: "employer", number: 2, title: "Welcome", kind: "welcome" },
  { id: "enrollment", phase: "employer", number: 3, title: "Open enrollment", kind: "enrollment" },
  { id: "eligibility", phase: "employer", number: 4, title: "Eligibility", kind: "eligibility" },
  { id: "medical", phase: "rates", number: 5, title: "Medical plans", kind: "medical" },
  { id: "costs", phase: "rates", number: 6, title: "Your costs", kind: "costs" },
  { id: "ancillary", phase: "rates", number: 7, title: "Dental & vision", kind: "ancillary" },
  { id: "telemedicine", phase: "documents", number: 8, title: "Telemedicine", kind: "module" },
  { id: "accounts", phase: "documents", number: 9, title: "Savings accounts", kind: "accounts" },
  { id: "life", phase: "documents", number: 10, title: "Life & AD&D", kind: "module" },
  { id: "income", phase: "documents", number: 11, title: "Income protection", kind: "module" },
  { id: "wellbeing", phase: "documents", number: 12, title: "EAP & voluntary", kind: "module" },
  { id: "contacts", phase: "employer", number: 13, title: "Contacts", kind: "contacts" },
  { id: "legal", phase: "employer", number: 14, title: "Legal", kind: "legal" },
];

export const checkDefinitions = [
  { id: "employer-name", phase: "employer", group: "Base booklet", label: "Employer name found" },
  { id: "plan-year", phase: "employer", group: "Base booklet", label: "Plan year found" },
  { id: "eligibility", phase: "employer", group: "Base booklet", label: "Eligibility rule found" },
  { id: "legal", phase: "employer", group: "Base booklet", label: "Legal disclaimer included" },
  { id: "carrier", phase: "rates", group: "Medical", label: "Carrier and plan matched" },
  { id: "rates", phase: "rates", group: "Medical", label: "Four coverage tiers normalized" },
  { id: "contribution", phase: "rates", group: "Costs", label: "Employer contribution mode found" },
  { id: "benefits", phase: "documents", group: "Medical", label: "Deductible and OOP max found" },
  { id: "copays", phase: "documents", group: "Medical", label: "Copays and Rx tiers found" },
  { id: "hsa", phase: "documents", group: "Medical", label: "HSA-qualified status checked" },
];

export const sourceDefinitions = [
  { phase: "employer", label: "Big Tows employer application", detail: "Employer facts · Primary", confidence: 98 },
  { phase: "rates", label: "2026 renewal rates", detail: "Rates and contributions · Primary", confidence: 96 },
  { phase: "documents", label: "Excellus Bronze HSA SBC", detail: "Official benefits · Authoritative", confidence: 99 },
  { phase: "instructions", label: "Broker final decisions", detail: "Overrides · Highest priority", confidence: 92 },
];
