import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Building2,ChevronRight,ArrowLeft,HeartPulse,Smile,Eye,BookOpen,Save,Check,CalendarDays,LoaderCircle}from'lucide-react';
import{companies as seedCompanies}from'./data';import'./styles.css';import'./inline.css';
const tiers=['EE','EE + Spouse','EE + Children','EE + Family'];
const fmt=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
const fmt2=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2}).format(n||0);
function path(){return location.pathname.split('/').filter(Boolean)}
function go(to,setRoute){history.pushState({},'',to);setRoute(path())}
function calculate(plan,pays=52){let rows=plan.tiers.map((r,i)=>{let er=r.premium*r.erPercent,ee=r.premium-er;return{...r,tier:r.tier||tiers[i],er,ee,perPay:ee*12/pays,erAnnual:er*r.enrolled*12,eeAnnual:ee*r.enrolled*12,total:r.premium*r.enrolled*12}});return{...plan,rows,enrolled:rows.reduce((a,r)=>a+r.enrolled,0),er:rows.reduce((a,r)=>a+r.erAnnual,0),ee:rows.reduce((a,r)=>a+r.eeAnnual,0),total:rows.reduce((a,r)=>a+r.total,0)}}
function App(){const[route,setRoute]=useState(path()),[companies,setCompanies]=useState(()=>{let saved=JSON.parse(localStorage.getItem('benefits-companies')||'null');return(saved||seedCompanies).filter(c=>c.id==='big-tows')});useEffect(()=>{let f=()=>setRoute(path());addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);let ordered=[...companies].sort((a,b)=>a.renewalDate.localeCompare(b.renewalDate)),company=companies.find(c=>c.id===route[1]);let update=updated=>setCompanies(cs=>{let next=cs.map(c=>c.id===updated.id?updated:c);localStorage.setItem('benefits-companies',JSON.stringify(next));return next});return <div><Header onHome={()=>go('/',setRoute)}/>{route.length===0?<Directory companies={ordered} open={id=>go(`/companies/${id}`,setRoute)}/>:company?<Company company={company} onUpdate={update} back={()=>go('/',setRoute)}/>:<Directory companies={ordered} open={id=>go(`/companies/${id}`,setRoute)}/>}</div>}
function Header({onHome}){return <header><button className="brand" onClick={onHome}><span>B</span><div><b>Benefits Studio</b><small>Company benefits workspace</small></div></button><button className="outline"><BookOpen/> Generate booklet <i>Coming soon</i></button></header>}
function Loading(){return <div className="loading"><LoaderCircle/><span>Loading benefit companies…</span></div>}
function Directory({companies,open}){return <main><Title eyebrow="Client directory" title="Companies" sub="Benefit plans ordered by upcoming renewal period."/><div className="companyList">{companies.map((c,i)=><button className="companyRow" onClick={()=>open(c.id)}><div className="companyIcon"><Building2/></div><div className="companyName"><b>{c.name}</b><span>{c.employeeCount||0} enrolled employees · {Object.keys(c.benefits||{}).length} benefit types</span></div><div className="renewal"><small>Renewal period</small><b><CalendarDays/>{c.renewalLabel}</b></div><span className={i===0?'status soon':'status'}>{i===0?'Next renewal':'Upcoming'}</span><ChevronRight/></button>)}</div></main>}
function Company({company,onUpdate,back}){const[expanded,setExpanded]=useState(null);let cards=[['health','Health',HeartPulse,'Medical coverage and contribution comparison'],['dental','Dental',Smile,'Dental coverage and contribution comparison'],['vision','Vision',Eye,'No plans configured']];return <main><Back onClick={back}/><Title eyebrow={company.name} title="Benefit plans" sub={`Renewal period ${company.renewalLabel}`}/><div className="benefitStack">{cards.map(([key,name,Icon,sub])=>{let active=!!company.benefits?.[key],open=expanded===key;return <button className={`benefitCard ${active?'':'disabled'} ${open?'selected':''}`} onClick={()=>active&&setExpanded(open?null:key)}><span className={`benefitIcon ${key}`}><Icon/></span><div><b>{name}</b><p>{sub}</p>{active?<span>{company.benefits[key].years.join(' vs ')} · {open?'Hide comparison':'View comparison'}</span>:<span>Not offered</span>}</div>{active&&<ChevronRight/>}</button>})}</div>{expanded&&<div className="expandedForm"><Plans key={expanded} company={company} type={expanded} onUpdate={onUpdate}/></div>}</main>}
function Plans({company,type,onUpdate}){let benefit=company.benefits[type],[pays,setPays]=useState(52),[data,setData]=useState(benefit.plans),[saved,setSaved]=useState(false);let current=useMemo(()=>data.map(p=>calculate(p,pays)),[data,pays]);let update=(pi,ri,key,v)=>setData(ds=>ds.map((p,i)=>i!==pi?p:{...p,tiers:p.tiers.map((r,j)=>j!==ri?r:{...r,[key]:v})}));let save=()=>{let updated={...company,benefits:{...company.benefits,[type]:{...benefit,plans:data}}};onUpdate(updated);setSaved(true);setTimeout(()=>setSaved(false),1500)};return <div className="inlinePlans"><div className="pageHead"><Title eyebrow={`${company.name} · ${type}`} title={`${type[0].toUpperCase()+type.slice(1)} year-over-year`} sub="Edit highlighted fields to compare the current renewal against the prior year."/><div className="controls"><label>Pay periods<select value={pays} onChange={e=>setPays(+e.target.value)}><option>52</option><option>26</option><option>24</option><option>12</option></select></label><button className="primary" onClick={save}>{saved?<Check/>:<Save/>}{saved?'Saved':'Save changes'}</button></div></div><Comparison plans={current} update={update}/></div>}
function Comparison({plans,update}){let all=plans.reduce((a,p)=>({er:a.er+p.er,ee:a.ee+p.ee,total:a.total+p.total,enrolled:a.enrolled+p.enrolled}),{er:0,ee:0,total:0,enrolled:0});let last=plans[0],now=plans[1]||plans[0],delta=now.total-last.total;return <><section className="stats"><Stat label="Current annual premium" value={fmt(now.total)}/><Stat label="Prior annual premium" value={fmt(last.total)}/><Stat label="Annual difference" value={`${delta>=0?'+':''}${fmt(delta)}`} tone={delta>0?'up':'down'}/><Stat label="Premium change" value={`${last.total?((delta/last.total)*100).toFixed(1):'0.0'}%`} tone={delta>0?'up':'down'}/></section><section className="tableCard"><div className="tableTitle"><div><h2>{plans.map(p=>p.year).join(' vs ')} Cost Summary</h2><p>Premium, employer percentage, and enrollment fields are editable.</p></div><span>Editable input</span></div><table><thead><tr><th>Plan</th><th>Tier</th><th>Monthly premium</th><th>ER cost</th><th>EE cost</th><th>EE per pay</th><th>ER %</th><th># enrolled</th><th>ER annual</th><th>EE annual</th><th>Total annual premium</th></tr></thead><tbody>{plans.flatMap((p,pi)=>[...p.rows.map((r,ri)=><tr><td>{ri===0?<b>{p.name}</b>:''}</td><td>{r.tier}</td><td><NumberField prefix="$" value={r.premium} change={v=>update(pi,ri,'premium',v)}/></td><td>{fmt2(r.er)}</td><td>{fmt2(r.ee)}</td><td>{fmt2(r.perPay)}</td><td><NumberField suffix="%" value={Math.round(r.erPercent*10000)/100} change={v=>update(pi,ri,'erPercent',v/100)}/></td><td><NumberField value={r.enrolled} change={v=>update(pi,ri,'enrolled',v)}/></td><td>{fmt(r.erAnnual)}</td><td>{fmt(r.eeAnnual)}</td><td><b>{fmt(r.total)}</b></td></tr>),<tr className="total"><td>{p.year} total</td><td colSpan="6"></td><td>{p.enrolled}</td><td>{fmt(p.er)}</td><td>{fmt(p.ee)}</td><td>{fmt(p.total)}</td></tr>])}</tbody></table></section></>}
function NumberField({value,change,prefix,suffix}){return <label className="number">{prefix}<input type="number" step="any" value={value} onChange={e=>change(+e.target.value)}/>{suffix}</label>}
function Title({eyebrow,title,sub}){return <div className="title"><span>{eyebrow}</span><h1>{title}</h1><p>{sub}</p></div>};function Back({onClick}){return <button className="back" onClick={onClick}><ArrowLeft/>Back</button>};function Stat({label,value,tone}){return <div className="stat"><span>{label}</span><b className={tone||''}>{value}</b></div>}
createRoot(document.getElementById('root')).render(<App/>);
